Repository julep-ai/julep, pull requests merged in 2024-12, with the labels that each got.

#968 Developers queries
  agents-api/agents_api/app.py
  agents-api/agents_api/clients/pg.py
  agents-api/agents_api/dependencies/developer_id.py
  agents-api/agents_api/queries/developers/__init__.py
  agents-api/agents_api/queries/developers/create_developer.py
  agents-api/agents_api/queries/developers/patch_developer.py
  agents-api/agents_api/queries/developers/update_developer.py
  agents-api/agents_api/queries/utils.py
  agents-api/agents_api/web.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_developer_queries.py
  agents-api/tests/test_user_queries.py
Labels: Review effort [1-5]: 4

#969 fix(agents-api): Bug fixes in sessions
  agents-api/agents_api/activities/execute_system.py
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/models/chat/prepare_chat_context.py
  agents-api/agents_api/models/session/create_session.py
  agents-api/agents_api/models/session/get_session.py
  agents-api/agents_api/models/session/prepare_session_data.py
  agents-api/agents_api/models/session/update_session.py
  agents-api/agents_api/models/utils.py
Labels: Review effort [1-5]: 3

#971 feat(agents-api): implement agent queries
  agents-api/agents_api/queries/agents/__init__.py
  agents-api/agents_api/queries/agents/create_agent.py
  agents-api/agents_api/queries/agents/create_or_update_agent.py
  agents-api/agents_api/queries/agents/delete_agent.py
  agents-api/agents_api/queries/agents/get_agent.py
  agents-api/agents_api/queries/agents/list_agents.py
  agents-api/agents_api/queries/agents/patch_agent.py
  agents-api/agents_api/queries/agents/update_agent.py
  agents-api/agents_api/queries/utils.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_agent_queries.py
Labels: Review effort [1-5]: 4

#972 fix(agents-api): Session & system tool fixes
  agents-api/agents_api/activities/execute_system.py
  agents-api/agents_api/common/protocol/sessions.py
Labels: Review effort [1-5]: 2

#973 fix(memory-store): Change association structure of files and docs
  memory-store/migrations/000005_files.down.sql
  memory-store/migrations/000005_files.up.sql
  memory-store/migrations/000006_docs.down.sql
  memory-store/migrations/000006_docs.up.sql
Labels: Review effort [1-5]: 3

#975 chore(agents-api): Add `/healthz` endpoint
  agents-api/agents_api/routers/healthz/__init__.py
  agents-api/agents_api/routers/healthz/check_health.py
  agents-api/agents_api/routers/healthz/router.py
  agents-api/agents_api/web.py
  gateway/traefik.yml.template
Labels: Review effort [1-5]: 2

#970 wip(agents-api): Add session sql queries
  agents-api/agents_api/app.py
  agents-api/agents_api/autogen/Entries.py
  agents-api/agents_api/autogen/Sessions.py
  agents-api/agents_api/autogen/openapi_model.py
  agents-api/agents_api/env.py
  agents-api/agents_api/queries/__init__.py
  agents-api/agents_api/queries/agents/__init__.py
  agents-api/agents_api/queries/agents/create_agent.py
  agents-api/agents_api/queries/agents/create_or_update_agent.py
  agents-api/agents_api/queries/agents/delete_agent.py
  agents-api/agents_api/queries/agents/get_agent.py
  agents-api/agents_api/queries/agents/list_agents.py
  agents-api/agents_api/queries/agents/patch_agent.py
  agents-api/agents_api/queries/agents/update_agent.py
  agents-api/agents_api/queries/developers/__init__.py
  agents-api/agents_api/queries/developers/create_developer.py
  agents-api/agents_api/queries/developers/get_developer.py
  agents-api/agents_api/queries/developers/patch_developer.py
  agents-api/agents_api/queries/developers/update_developer.py
  agents-api/agents_api/queries/entries/__init__.py
  agents-api/agents_api/queries/entries/create_entries.py
  agents-api/agents_api/queries/entries/delete_entries.py
  agents-api/agents_api/queries/entries/get_history.py
  agents-api/agents_api/queries/entries/list_entries.py
  agents-api/agents_api/queries/sessions/__init__.py
  agents-api/agents_api/queries/sessions/count_sessions.py
  agents-api/agents_api/queries/sessions/create_or_update_session.py
  agents-api/agents_api/queries/sessions/create_session.py
  agents-api/agents_api/queries/sessions/delete_session.py
  agents-api/agents_api/queries/sessions/get_session.py
  agents-api/agents_api/queries/sessions/list_sessions.py
  agents-api/agents_api/queries/sessions/patch_session.py
  agents-api/agents_api/queries/sessions/update_session.py
  agents-api/agents_api/queries/users/create_or_update_user.py
  agents-api/agents_api/queries/users/create_user.py
  agents-api/agents_api/queries/users/delete_user.py
  agents-api/agents_api/queries/users/get_user.py
  agents-api/agents_api/queries/users/list_users.py
  agents-api/agents_api/queries/users/patch_user.py
  agents-api/agents_api/queries/users/update_user.py
  agents-api/agents_api/queries/utils.py
  agents-api/agents_api/web.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_agent_queries.py
  agents-api/tests/test_developer_queries.py
  agents-api/tests/test_entry_queries.py
  agents-api/tests/test_messages_truncation.py
  agents-api/tests/test_session_queries.py
  agents-api/tests/test_user_queries.py
  agents-api/tests/utils.py
  integrations-service/integrations/autogen/Entries.py
  integrations-service/integrations/autogen/Sessions.py
  memory-store/migrations/000009_sessions.up.sql
  memory-store/migrations/000015_entries.up.sql
  memory-store/migrations/000016_entry_relations.up.sql
  typespec/entries/models.tsp
  typespec/sessions/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 4

#982 Tools queries
  agents-api/agents_api/exceptions.py
  agents-api/agents_api/models/chat/get_cached_response.py
  agents-api/agents_api/models/chat/prepare_chat_context.py
  agents-api/agents_api/models/chat/set_cached_response.py
  agents-api/agents_api/models/tools/create_tools.py
  agents-api/agents_api/models/tools/delete_tool.py
  agents-api/agents_api/models/tools/get_tool.py
  agents-api/agents_api/models/tools/get_tool_args_from_metadata.py
  agents-api/agents_api/models/tools/list_tools.py
  agents-api/agents_api/models/tools/update_tool.py
  agents-api/agents_api/queries/chat/__init__.py
  agents-api/agents_api/queries/chat/gather_messages.py
  agents-api/agents_api/queries/chat/prepare_chat_context.py
  agents-api/agents_api/queries/tools/__init__.py
  agents-api/agents_api/queries/tools/create_tools.py
  agents-api/agents_api/queries/tools/delete_tool.py
  agents-api/agents_api/queries/tools/get_tool.py
  agents-api/agents_api/queries/tools/get_tool_args_from_metadata.py
  agents-api/agents_api/queries/tools/list_tools.py
  agents-api/agents_api/queries/tools/patch_tool.py
  agents-api/agents_api/queries/tools/update_tool.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_tool_queries.py
Labels: Review effort [1-5]: 4

#985 F/dsearch queries: Add doc search sql queries
  agents-api/agents_api/queries/docs/__init__.py
  agents-api/agents_api/queries/docs/search_docs_by_embedding.py
  agents-api/agents_api/queries/docs/search_docs_by_text.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  agents-api/agents_api/queries/tools/__init__.py
  agents-api/agents_api/queries/tools/create_tools.py
  agents-api/agents_api/queries/tools/delete_tool.py
  agents-api/agents_api/queries/tools/get_tool.py
  agents-api/agents_api/queries/tools/get_tool_args_from_metadata.py
  agents-api/agents_api/queries/tools/list_tools.py
  agents-api/agents_api/queries/tools/patch_tool.py
  agents-api/agents_api/queries/tools/update_tool.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_docs_queries.py
  memory-store/migrations/000018_doc_search.up.sql
Labels: Review effort [1-5]: 4

#992 fix(agents-api): Fix tools tests
  agents-api/tests/fixtures.py
  agents-api/tests/test_task_queries.py
  agents-api/tests/test_tool_queries.py
Labels: Review effort [1-5]: 4

#994 fix(agents-api, memory-store): fix temporal workflows, queries, and migrations
  agents-api/agents_api/activities/task_steps/transition_step.py
  agents-api/agents_api/clients/temporal.py
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/queries/agents/create_or_update_agent.py
  agents-api/agents_api/queries/executions/get_temporal_workflow_data.py
  agents-api/agents_api/queries/executions/prepare_execution_input.py
  agents-api/agents_api/queries/tasks/create_or_update_task.py
  agents-api/agents_api/queries/tasks/get_task.py
  agents-api/agents_api/queries/tools/get_tool_args_from_metadata.py
  agents-api/agents_api/routers/tasks/create_task_execution.py
  agents-api/agents_api/worker/__main__.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/docker-compose.yml
  agents-api/tests/fixtures.py
  agents-api/tests/test_execution_workflow.py
  agents-api/tests/test_task_routes.py
  memory-store/docker-compose.yml
  memory-store/migrations/000012_transitions.up.sql
  memory-store/migrations/000013_executions_continuous_view.up.sql
  memory-store/migrations/000019_system_developer.down.sql
Labels: Review effort [1-5]: 4

#998 fix(agents-api): Fix tests for workflows
  agents-api/agents_api/activities/container.py
  agents-api/agents_api/activities/execute_integration.py
  agents-api/agents_api/activities/execute_system.py
  agents-api/agents_api/activities/task_steps/pg_query_step.py
  agents-api/agents_api/activities/task_steps/transition_step.py
  agents-api/agents_api/app.py
  agents-api/agents_api/worker/__main__.py
  agents-api/agents_api/worker/worker.py
  agents-api/tests/test_execution_workflow.py
Labels: Review effort [1-5]: 4

#1001 chore: misc test and queries fixes
  agents-api/agents_api/common/utils/db_exceptions.py
  agents-api/agents_api/queries/executions/list_execution_transitions.py
  agents-api/agents_api/queries/tasks/create_or_update_task.py
  agents-api/agents_api/queries/tasks/update_task.py
  agents-api/agents_api/routers/healthz/__init__.py
  agents-api/agents_api/routers/healthz/router.py
  agents-api/agents_api/routers/jobs/__init__.py
  agents-api/agents_api/routers/tasks/__init__.py
  agents-api/agents_api/routers/tasks/create_task_execution.py
  agents-api/agents_api/routers/tasks/list_execution_transitions.py
  agents-api/agents_api/web.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_docs_routes.py
  agents-api/tests/test_task_routes.py
Labels: Review effort [1-5]: 2

#1000 Fix(agents-api): Miscellaneous fixes related to sessions & entries
  agents-api/agents_api/queries/chat/gather_messages.py
  agents-api/agents_api/queries/docs/list_docs.py
  agents-api/agents_api/queries/docs/search_docs_by_embedding.py
  agents-api/agents_api/queries/docs/search_docs_by_text.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  agents-api/agents_api/queries/docs/utils.py
  agents-api/agents_api/queries/entries/create_entries.py
  agents-api/agents_api/queries/entries/get_history.py
  agents-api/agents_api/queries/sessions/create_or_update_session.py
  agents-api/agents_api/queries/sessions/patch_session.py
  agents-api/agents_api/queries/sessions/update_session.py
  agents-api/agents_api/routers/docs/create_doc.py
  agents-api/agents_api/routers/docs/search_docs.py
  memory-store/migrations/000015_entries.up.sql
Labels: Review effort [1-5]: 3

#980 Update README.md
  cookbooks/README.md
Labels: Review effort [1-5]: 1
