Repository julep-ai/julep, pull requests merged in 2025-05, with the labels that each got.

#1345 fix: Check if developer is active
  agents-api/agents_api/queries/developers/get_developer.py
Labels: Review effort 1/5

#1346 dev->main
  agents-api/agents_api/queries/developers/get_developer.py
Labels: Review effort 1/5

#1348 feat: Add inactive user reject middleware
  agents-api/agents_api/dependencies/developer_id.py
  agents-api/tests/test_developer_queries.py
Labels: Review effort 2/5

#1351 Developers and costs check
  agents-api/agents_api/dependencies/developer_id.py
  agents-api/agents_api/env.py
  agents-api/agents_api/queries/developers/get_developer.py
  agents-api/agents_api/queries/usage/__init__.py
  agents-api/agents_api/queries/usage/create_usage_record.py
  agents-api/agents_api/queries/usage/get_user_cost.py
  agents-api/agents_api/web.py
  agents-api/tests/test_developer_queries.py
  agents-api/tests/test_middleware.py
  agents-api/tests/test_usage_cost.py
  agents-api/tests/test_usage_tracking.py
  memory-store/migrations/000038_usage_cost_monthly.down.sql
  memory-store/migrations/000038_usage_cost_monthly.up.sql
Labels: Review effort 3/5

#1355 dev -> main (May 5th)
  agents-api/agents_api/env.py
  agents-api/agents_api/queries/developers/get_developer.py
  agents-api/agents_api/queries/usage/__init__.py
  agents-api/agents_api/queries/usage/create_usage_record.py
  agents-api/agents_api/queries/usage/get_user_cost.py
  agents-api/agents_api/web.py
  agents-api/tests/test_developer_queries.py
  agents-api/tests/test_middleware.py
  agents-api/tests/test_usage_cost.py
  agents-api/tests/test_usage_tracking.py
  memory-store/migrations/000038_usage_cost_monthly.down.sql
  memory-store/migrations/000038_usage_cost_monthly.up.sql
Labels: Review effort 3/5

#1334 fix(documentation): Add missing Node.js examples + misc fixes
  documentation/concepts/agents.mdx
  documentation/concepts/docs.mdx
  documentation/concepts/tasks.mdx
  documentation/integrations/supported-models.mdx
Labels: Review effort 2/5

#1357 fix(agents-api): remove limit parameter from list transition in workflow
  agents-api/agents_api/common/protocol/tasks.py
Labels: Review effort 1/5

#1358 doc: Add CLAUDE.md files and anchor comments
  CLAUDE.md
  CONTRIBUTING.md
  agents-api/CLAUDE.md
  agents-api/agents_api/activities/CLAUDE.md
  agents-api/agents_api/activities/task_steps/__init__.py
  agents-api/agents_api/activities/task_steps/base_evaluate.py
  agents-api/agents_api/activities/task_steps/prompt_step.py
  agents-api/agents_api/activities/task_steps/tool_call_step.py
  agents-api/agents_api/autogen/CLAUDE.md
  agents-api/agents_api/clients/CLAUDE.md
  agents-api/agents_api/common/CLAUDE.md
  agents-api/agents_api/common/exceptions/agents.py
  agents-api/agents_api/common/exceptions/executions.py
  agents-api/agents_api/common/exceptions/sessions.py
  agents-api/agents_api/common/exceptions/tasks.py
  agents-api/agents_api/common/exceptions/tools.py
  agents-api/agents_api/common/exceptions/users.py
  agents-api/agents_api/common/exceptions/validation.py
  agents-api/agents_api/common/protocol/models.py
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/common/utils/workflows.py
  agents-api/agents_api/queries/CLAUDE.md
  agents-api/agents_api/queries/__init__.py
  agents-api/agents_api/queries/agents/__init__.py
  agents-api/agents_api/queries/chat/__init__.py
  agents-api/agents_api/queries/developers/__init__.py
  agents-api/agents_api/queries/docs/__init__.py
  agents-api/agents_api/queries/executions/__init__.py
  agents-api/agents_api/queries/tools/__init__.py
  agents-api/agents_api/queries/usage/__init__.py
  agents-api/agents_api/queries/utils.py
  agents-api/agents_api/routers/CLAUDE.md
  agents-api/agents_api/routers/__init__.py
  agents-api/agents_api/routers/agents/create_agent.py
  agents-api/agents_api/routers/agents/get_agent_details.py
  agents-api/agents_api/routers/sessions/create_session.py
  agents-api/agents_api/routers/sessions/get_session.py
  agents-api/agents_api/routers/sessions/list_sessions.py
  agents-api/agents_api/routers/tasks/__init__.py
  agents-api/agents_api/routers/tasks/create_task_execution.py
  agents-api/agents_api/routers/utils/model_converters.py
  agents-api/agents_api/routers/utils/model_validation.py
  agents-api/agents_api/worker/CLAUDE.md
  agents-api/agents_api/workflows/CLAUDE.md
  agents-api/agents_api/workflows/__init__.py
  agents-api/agents_api/workflows/demo.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  cli/CLAUDE.md
  documentation/CLAUDE.md
  integrations-service/CLAUDE.md
  memory-store/CLAUDE.md
  typespec/CLAUDE.md
Labels: Review effort 2/5

#1362 fix: Fix entities views
  agents-api/agents_api/env.py
  memory-store/migrations/000039_projects.up.sql
Labels: Review effort 3/5

#1359 chore(agents-api): optimize inputs retreival in prepare_for_step
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/queries/executions/__init__.py
  agents-api/agents_api/queries/executions/list_execution_inputs_data.py
  agents-api/agents_api/queries/executions/list_execution_state_data.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_prepare_for_step.py
  agents-api/tests/test_task_execution_workflow.py
  agents-api/tests/test_transitions_queries.py
Labels: Review effort 3/5

#1369 feat(agents-api): add decryption flag to secrets queries
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/common/utils/secrets.py
  agents-api/agents_api/queries/secrets/get_by_name.py
  agents-api/agents_api/queries/secrets/list.py
  agents-api/agents_api/routers/sessions/render.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_secrets_queries.py
  agents-api/tests/test_secrets_routes.py
Labels: Review effort 2/5

#1370 docs: fix parameters typo
  documentation/integrations/supported-models.mdx
Labels: codex

#1374 Fix mmr doc order bug
  agents-api/agents_api/common/utils/mmr.py
  agents-api/agents_api/queries/projects/__init__.py
Labels: codex

#1371 Update import command docstring
  cli/src/julep_cli/importt.py
Labels: codex

#1372 Add developer orientation doc
  documentation/docs.json
  documentation/introduction/developer-orientation.mdx
Labels: Review effort 1/5, codex

#1375 Add cookbook links in docs
  CHANGELOG.md
  documentation/guides/cookbooks/community-examples.mdx
  documentation/guides/cookbooks/industry-solutions.mdx
  documentation/guides/cookbooks/quick-solutions.mdx
Labels: codex

#1376 Split trip planning tutorial
  documentation/docs.json
  documentation/tutorials/trip-planning-input.mdx
  documentation/tutorials/trip-planning-running.mdx
  documentation/tutorials/trip-planning-tools.mdx
  documentation/tutorials/trip-planning-workflow.mdx
  documentation/tutorials/trip-planning.mdx
Labels: codex

#1366 docs: Update local setup, secrets, and type of task steps documentation
  documentation/advanced/agentic-patterns.mdx
  documentation/advanced/chat.mdx
  documentation/advanced/lifecycle.mdx
  documentation/advanced/localsetup.mdx
  documentation/advanced/render.mdx
  documentation/advanced/secrets-management.mdx
  documentation/advanced/types-of-task-steps.mdx
  documentation/concepts/agents.mdx
  documentation/concepts/docs.mdx
  documentation/concepts/secrets.mdx
  documentation/concepts/sessions.mdx
  documentation/concepts/tasks.mdx
  documentation/guides/advanced/integration-patterns.mdx
  documentation/guides/getting-started/chat-with-an-agent.mdx
  documentation/guides/getting-started/create-and-execute-julep-task.mdx
  documentation/integrations/communicationdata/email.mdx
  documentation/integrations/mediafile/cloudinary.mdx
  documentation/integrations/mediafile/llamaparse.mdx
  documentation/integrations/webbrowser/remote-browser.mdx
  documentation/introduction/quickstart.mdx
  documentation/julepcli/commands.mdx
  documentation/responses/cli.mdx
  documentation/responses/concepts.mdx
  documentation/responses/examples.mdx
  documentation/sdks/common/secrets.mdx
  documentation/sdks/index.mdx
  documentation/sdks/nodejs/advanced-usage.mdx
  documentation/sdks/nodejs/agents.mdx
  documentation/sdks/nodejs/secrets.mdx
  documentation/sdks/nodejs/tasks.mdx
  documentation/sdks/nodejs/tools-integration.mdx
  documentation/sdks/python/advanced-usage.mdx
  documentation/sdks/python/agents.mdx
  documentation/sdks/python/secrets.mdx
  documentation/sdks/python/sessions.mdx
  documentation/sdks/python/tasks.mdx
  documentation/sdks/python/tools-integration.mdx
  documentation/tutorials/browser-use.mdx
  documentation/tutorials/rag-chatbot.mdx
  documentation/tutorials/trip-planning.mdx
  documentation/tutorials/video-processing.mdx
Labels: Review effort 2/5

#1380 docs: dev journey guides + architecture diagram
  documentation/advanced/architecture-deep-dive.mdx
  documentation/docs.json
  documentation/guides/adding-tool-integration.mdx
  documentation/guides/modifying-agent-workflow.mdx
  documentation/images/architecture-diagram.svg
Labels: codex

#1387 Define CLI tool models
  cli/src/julep_cli/models.py
  cli/src/julep_cli/tool_models.py
Labels: Review effort 2/5, codex

#1383 Update changelog for get_live_urls
  CHANGELOG.md
Labels: Review effort 1/5, codex

#1382 Clean up .gitignore
  .gitignore
Labels: codex

#1392 Update roadmap and CLI docs
  documentation/julepcli/commands.mdx
  documentation/responses/roadmap.mdx
Labels: Review effort 1/5, codex

#1393 Trim notebooks and tidy yaml
  cookbooks/advanced/00-Devfest-Email-Assistant.ipynb
  cookbooks/advanced/01-website-crawler.ipynb
  cookbooks/advanced/02-sarcastic-news-headline-generator.ipynb
  cookbooks/advanced/03-trip-planning-assistant.ipynb
  cookbooks/advanced/05-video-processing-with-natural-language.ipynb
  cookbooks/advanced/06-browser-use.ipynb
  cookbooks/advanced/07-personalized-research-assistant.ipynb
  cookbooks/advanced/09-companion-agent.ipynb
  cookbooks/basics/01-Hello-Agent.ipynb
  cookbooks/basics/02-Simple-Task.ipynb
  cookbooks/basics/03-Adding-Tools.ipynb
  cookbooks/basics/04-Parallel-Steps.ipynb
  cookbooks/basics/05-RAG-and-Docs.ipynb
  deploy/standalone-docker-compose.yaml
  documentation/guides/getting-started/create-and-execute-julep-task.mdx
Labels: Review effort 2/5, codex

#1381 Rename CLAUDE docs
  .agentignore
  .agentindexignore
  .cursorignore
  .cursorindexignore
  AGENTS.md
  CLAUDE.md
  agents-api/AGENTS.md
  agents-api/CLAUDE.md
  agents-api/agents_api/activities/AGENTS.md
  agents-api/agents_api/activities/CLAUDE.md
  agents-api/agents_api/autogen/AGENTS.md
  agents-api/agents_api/autogen/CLAUDE.md
  agents-api/agents_api/clients/AGENTS.md
  agents-api/agents_api/clients/CLAUDE.md
  agents-api/agents_api/common/AGENTS.md
  agents-api/agents_api/common/CLAUDE.md
  agents-api/agents_api/queries/AGENTS.md
  agents-api/agents_api/queries/CLAUDE.md
  agents-api/agents_api/routers/AGENTS.md
  agents-api/agents_api/routers/CLAUDE.md
  agents-api/agents_api/worker/AGENTS.md
  agents-api/agents_api/worker/CLAUDE.md
  agents-api/agents_api/workflows/AGENTS.md
  agents-api/agents_api/workflows/CLAUDE.md
  cli/AGENTS.md
  cli/CLAUDE.md
  documentation/AGENTS.md
  documentation/CLAUDE.md
  integrations-service/AGENTS.md
  integrations-service/CLAUDE.md
  memory-store/AGENTS.md
  memory-store/CLAUDE.md
  typespec/AGENTS.md
  typespec/CLAUDE.md
Labels: Review effort 2/5, codex

#1396 Remove unused ruff noqa
  agents-api/agents_api/queries/projects/__init__.py
Labels: Review effort 1/5, codex

#1373 fix: prevent blocking call in get_live_urls
  CHANGELOG.md
  agents-api/agents_api/common/utils/mmr.py
  agents-api/tests/test_mmr.py
  integrations-service/integrations/utils/integrations/browserbase.py
Labels: Review effort 2/5, codex

#1412 Update query anchor notes
  agents-api/agents_api/queries/AGENTS.md
  agents-api/agents_api/queries/sessions/count_sessions.py
  agents-api/agents_api/queries/sessions/create_session.py
Labels: Review effort 1/5, codex

#1433 feat(.github): Create translate-readme workflow using claude action
  .github/workflows/translate-readme.yml
Labels: Review effort 2/5

#1437 docs: updage changelog.md
  CHANGELOG.md
Labels: Review effort 1/5

#1438 chore: Update CHANGELOG.md
  CHANGELOG.md
Labels: Review effort 1/5

#1439 fix(blob-store): add an extra seaweedfs volume, switch docker composes
  CHANGELOG.md
  blob-store/docker-compose-ha.yml
  docker-compose.yml
Labels: Review effort 2/5

#1443 fix(agents-api): supress bucket errors on s3 client setup
  agents-api/agents_api/clients/async_s3.py
  agents-api/agents_api/clients/sync_s3.py
Labels: Review effort 2/5

#1444 dev -> main (s3 hotfix)
  CHANGELOG.md
  agents-api/agents_api/clients/async_s3.py
  agents-api/agents_api/clients/sync_s3.py
  blob-store/docker-compose-ha.yml
  docker-compose.yml
Labels: Review effort 2/5

#1414 Fix LLM bad request error handling
  agents-api/agents_api/web.py
Labels: Review effort 1/5, codex

#1448 Remove DEMO_API_KEY support
  CHANGELOG.md
  cookbooks/advanced/06-browser-use.ipynb
  cookbooks/advanced/07-personalized-research-assistant.ipynb
  documentation/advanced/types-of-task-steps.mdx
  integrations-service/integrations/utils/integrations/algolia.py
  integrations-service/integrations/utils/integrations/brave.py
  integrations-service/integrations/utils/integrations/browserbase.py
  integrations-service/integrations/utils/integrations/cloudinary.py
  integrations-service/integrations/utils/integrations/email.py
  integrations-service/integrations/utils/integrations/llama_parse.py
  integrations-service/integrations/utils/integrations/mailgun.py
  integrations-service/integrations/utils/integrations/spider.py
  integrations-service/integrations/utils/integrations/unstructured.py
  integrations-service/integrations/utils/integrations/weather.py
Labels: Review effort 2/5, codex

#1452 Fix broken cookbook footer links
  CHANGELOG.md
  documentation/concepts/sessions.mdx
  documentation/guides/cookbooks/community-examples.mdx
  documentation/guides/cookbooks/industry-solutions.mdx
  documentation/guides/cookbooks/quick-solutions.mdx
  documentation/tutorials/browser-use.mdx
  documentation/tutorials/rag-chatbot.mdx
  documentation/tutorials/trip-planning-running.mdx
  documentation/tutorials/trip-planning.mdx
  documentation/tutorials/video-processing.mdx
Labels: Review effort 1/5, codex

#1449 Mitigate DeadlockError
  agents-api/agents_api/worker/__main__.py
  documentation/concepts/tasks.mdx
Labels: Review effort 2/5

#1447 feat(agents-api): Add SSE endpoint for streaming execution status
  agents-api/agents_api/autogen/openapi_model.py
  agents-api/agents_api/env.py
  agents-api/agents_api/queries/executions/get_execution_status.py
  agents-api/agents_api/routers/tasks/__init__.py
  agents-api/agents_api/routers/tasks/stream_execution_status.py
  agents-api/docker-compose.yml
  agents-api/tests/test_task_routes.py
  documentation/concepts/execution.mdx
  typespec/executions/endpoints.tsp
  typespec/executions/models.tsp
  typespec/main.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 2/5

#1463 feat(llm-proxy): Add model fallback litellm-config.yaml
  llm-proxy/litellm-config.yaml
Labels: Review effort 1/5

#1464 dev -> main (May 29th)
  .github/workflows/claude.yml
  agents-api/AGENTS.md
  agents-api/agents_api/common/utils/db_exceptions.py
  agents-api/agents_api/queries/AGENTS.md
  agents-api/agents_api/routers/AGENTS.md
  agents-api/tests/test_session_routes.py
  blob-store/AGENTS.md
  blob-store/CLAUDE.md
  gateway/AGENTS.md
  gateway/CLAUDE.md
  integrations-service/AGENTS.md
  llm-proxy/AGENTS.md
  llm-proxy/CLAUDE.md
  llm-proxy/litellm-config.yaml
  monitoring/AGENTS.md
  monitoring/CLAUDE.md
  scheduler/AGENTS.md
  scheduler/CLAUDE.md
Labels: Review effort 2/5

#1367 Add chat streaming support
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/common/utils/usage.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/tests/test_chat_streaming.py
  typespec/chat/endpoints.tsp
  typespec/package-lock.json
  typespec/package.json
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5
