Repository julep-ai/julep, pull requests merged in 2025-08, with the labels that each got.

#1535 dev -> main (Aug 1st)
  .github/SUPPORT.md
  README.md
  changelog/dev/2025-07-31.md
  cookbooks/advanced/00-Devfest-Email-Assistant.ipynb
  cookbooks/advanced/01-website-crawler.ipynb
  cookbooks/advanced/02-sarcastic-news-headline-generator.ipynb
  cookbooks/advanced/03-trip-planning-assistant.ipynb
  cookbooks/advanced/05-video-processing-with-natural-language.ipynb
  cookbooks/advanced/06-browser-use.ipynb
  cookbooks/advanced/07-personalized-research-assistant.ipynb
  cookbooks/advanced/08-rag-chatbot.ipynb
  cookbooks/advanced/09-companion-agent.ipynb
  cookbooks/basics/01-Hello-Agent.ipynb
  cookbooks/basics/02-Simple-Task.ipynb
  cookbooks/basics/03-Adding-Tools.ipynb
  cookbooks/basics/04-Parallel-Steps.ipynb
  cookbooks/basics/05-RAG-and-Docs.ipynb
  documentation/AGENTS.md
  documentation/advanced/types-of-task-steps.mdx
  documentation/concepts/tools.mdx
  documentation/docs.json
  documentation/guides/getting-started/create-and-execute-julep-task.mdx
  documentation/images/julep_overview.svg
  documentation/integrations/supported-models.mdx
  documentation/introduction/julep.mdx
  documentation/scripts/entelligence-chat.js
  documentation/scripts/julep-chat-widget.js
  documentation/tutorials/browser-use.mdx
  documentation/tutorials/rag-chatbot.mdx
  documentation/tutorials/trip-planning-workflow.mdx
  documentation/tutorials/trip-planning.mdx
  documentation/tutorials/video-processing.mdx
  src/agents-api/agents_api/activities/task_steps/prompt_step.py
  src/agents-api/agents_api/common/protocol/tasks.py
  src/agents-api/agents_api/common/utils/secrets.py
  src/agents-api/tests/test_prepare_for_step.py
  src/agents-api/tests/test_prompt_step_auto_tools.py
  src/agents-api/tests/test_task_execution_workflow.py
  src/llm-proxy/litellm-config.yaml
Labels: Review effort 4/5, Possible security concern

#1536 Merge pull request #1331 from julep-ai/dev
  .github/workflows/claude.yml
  changelog/dev/2025-08-06.md
Labels: Review effort 1/5

#1537 feat(agents-api): add Llama model multiplier and update litellm-config.yaml
  .env.example
  changelog/dev/2025-08-07.md
  src/agents-api/agents_api/common/utils/usage.py
  src/agents-api/agents_api/env.py
  src/agents-api/agents_api/queries/usage/create_usage_record.py
  src/agents-api/docker-compose.yml
  src/agents-api/tests/test_usage_tracking.py
  src/llm-proxy/litellm-config.yaml
Labels: Review effort 3/5

#1538 chore(agents-api): migrate anthropic models to bedrock
  changelog/dev/2025-08-08.md
  src/agents-api/pyproject.toml
  src/agents-api/uv.lock
  src/llm-proxy/docker-compose.yml
  src/llm-proxy/litellm-config.yaml
Labels: Review effort 3/5, Possible security concern

#1539 dev -> main (Aug 8th)
  .env.example
  changelog/dev/2025-08-07.md
  changelog/dev/2025-08-08.md
  cookbooks/advanced/11-hacker-news-personalized-generator.ipynb
  documentation/docs.json
  documentation/integrations/supported-models.mdx
  documentation/tutorials/hacker-news-newsletter.mdx
  src/agents-api/agents_api/common/utils/usage.py
  src/agents-api/agents_api/env.py
  src/agents-api/agents_api/queries/usage/create_usage_record.py
  src/agents-api/docker-compose.yml
  src/agents-api/pyproject.toml
  src/agents-api/tests/test_usage_tracking.py
  src/agents-api/uv.lock
  src/llm-proxy/docker-compose.yml
  src/llm-proxy/litellm-config.yaml
Labels: Review effort 3/5, Possible security concern

#1541 dev -> main (Aug 17th)
  changelog/Templates/index-template/home-summary.html
  changelog/dev/2025-08-15.md
  documentation/integrations/supported-models.mdx
  src/llm-proxy/litellm-config.yaml
Labels: Review effort 2/5
