Repository julep-ai/julep, pull requests merged in 2025-07, with the labels that each got.

#1453 feat(agents-api, integrations-service): tool calls in tasks and sessions
  .env.example
  .gitignore
  changelog/dev/2025-06-30.md
  docker-compose.yml
  src/agents-api/agents_api/activities/execute_integration.py
  src/agents-api/agents_api/activities/execute_system.py
  src/agents-api/agents_api/activities/task_steps/prompt_step.py
  src/agents-api/agents_api/activities/tool_executor.py
  src/agents-api/agents_api/autogen/Tools.py
  src/agents-api/agents_api/autogen/openapi_model.py
  src/agents-api/agents_api/clients/__init__.py
  src/agents-api/agents_api/clients/feature_flags.py
  src/agents-api/agents_api/clients/integrations.py
  src/agents-api/agents_api/common/utils/feature_flags.py
  src/agents-api/agents_api/common/utils/tool_runner.py
  src/agents-api/agents_api/env.py
  src/agents-api/agents_api/workflows/task_execution/__init__.py
  src/agents-api/docker-compose.yml
  src/agents-api/pyproject.toml
  src/agents-api/tests/test_prompt_step_auto_tools.py
  src/agents-api/tests/test_tool_runner.py
  src/agents-api/uv.lock
  src/feature-flags/docker-compose.yml
  src/feature-flags/env.example
  src/integrations-service/integrations/autogen/Chat.py
  src/integrations-service/integrations/autogen/Entries.py
  src/integrations-service/integrations/autogen/Secrets.py
  src/integrations-service/integrations/autogen/Sessions.py
  src/integrations-service/integrations/autogen/Tasks.py
  src/integrations-service/integrations/autogen/Tools.py
  src/integrations-service/integrations/routers/integrations/get_integration_tool.py
  src/openapi.yaml
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/typespec/tools/models.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5, Possible security concern

#1515 feat(agents-api): integrate auto_run_tools with prompt step tool calling
  changelog/dev/2025-07-02.md
  src/agents-api/agents_api/activities/task_steps/prompt_step.py
  src/agents-api/agents_api/autogen/Tasks.py
  src/agents-api/tests/test_prompt_step_auto_tools.py
  src/agents-api/tests/test_task_execution_workflow.py
  src/integrations-service/integrations/autogen/Tasks.py
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/typespec/tasks/steps.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1516 feat(agents-api): implement auto tool calls in session chat
  changelog/dev/2025-07-03.md
  changelog/dev/2025-07-04.md
  src/agents-api/agents_api/activities/execute_integration.py
  src/agents-api/agents_api/activities/execute_system.py
  src/agents-api/agents_api/autogen/Chat.py
  src/agents-api/agents_api/autogen/Entries.py
  src/agents-api/agents_api/common/utils/tool_runner.py
  src/agents-api/agents_api/queries/chat/gather_messages.py
  src/agents-api/agents_api/queries/tools/get_tool_args_from_metadata.py
  src/agents-api/agents_api/routers/responses/create_response.py
  src/agents-api/agents_api/routers/sessions/auto_tools/__init__.py
  src/agents-api/agents_api/routers/sessions/auto_tools/chat.py
  src/agents-api/agents_api/routers/sessions/auto_tools/render.py
  src/agents-api/agents_api/routers/sessions/chat.py
  src/agents-api/agents_api/routers/sessions/legacy/__init__.py
  src/agents-api/agents_api/routers/sessions/legacy/chat.py
  src/agents-api/agents_api/routers/sessions/legacy/render.py
  src/agents-api/agents_api/routers/sessions/render.py
  src/agents-api/agents_api/workflows/task_execution/__init__.py
  src/agents-api/tests/test_chat_auto_tools.py
  src/agents-api/tests/test_chat_streaming.py
  src/agents-api/tests/test_secrets_usage.py
  src/agents-api/tests/test_task_execution_workflow.py
  src/integrations-service/integrations/autogen/Chat.py
  src/integrations-service/integrations/autogen/Entries.py
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/typespec/chat/models.tsp
  src/typespec/common/scalars.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5

#1519 docs: enhance documentation for automatic tool execution
  changelog/dev/2025-07-05.md
  documentation/advanced/chat.mdx
  documentation/advanced/types-of-task-steps.mdx
  documentation/concepts/sessions.mdx
  documentation/concepts/tools.mdx
  documentation/sdks/nodejs/tools-integration.mdx
  documentation/sdks/python/tools-integration.mdx
  src/agents-api/agents_api/routers/sessions/auto_tools/render.py
  src/agents-api/agents_api/routers/sessions/legacy/render.py
Labels: Review effort 2/5

#1524 feat(llm-proxy): add new Gemini models to configuration
  changelog/dev/2025-07-08.md
  src/llm-proxy/litellm-config.yaml
Labels: Review effort 1/5

#1528 fix(agents-api): properly handle custom-api-key and secrets api key
  changelog/dev/2025-07-09.md
  src/agents-api/agents_api/clients/litellm.py
  src/agents-api/agents_api/common/utils/llm_providers.py
  src/agents-api/agents_api/routers/sessions/auto_tools/render.py
  src/agents-api/agents_api/routers/sessions/legacy/render.py
  src/agents-api/tests/test_litellm_utils.py
Labels: Review effort 3/5

#1529 docs: better transparent supported models page
  .github/workflows/sync-model-docs.yml
  changelog/dev/2025-07-09.md
  documentation/integrations/supported-models.mdx
  src/scripts/sync_model_docs.py
Labels: Review effort 4/5, Possible security concern

#1530 fix(agents-api): remove ``continue_`` field + filter out ``name`` field for non openai models
  documentation/advanced/chat.mdx
  documentation/advanced/render.mdx
  src/agents-api/agents_api/activities/task_steps/prompt_step.py
  src/agents-api/agents_api/autogen/Chat.py
  src/agents-api/agents_api/autogen/Tasks.py
  src/integrations-service/integrations/autogen/Chat.py
  src/integrations-service/integrations/autogen/Tasks.py
  src/llm-proxy/litellm-config.yaml
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/typespec/entries/models.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1532 dev -> main (Jul 18th)
  .github/workflows/sync-model-docs.yml
  changelog/Templates/index-template/home-summary.html
  changelog/dev/2025-07-09.md
  changelog/stable (main)/2025-07-18.md
  documentation/advanced/chat.mdx
  documentation/advanced/render.mdx
  documentation/advanced/types-of-task-steps.mdx
  documentation/concepts/agents.mdx
  documentation/integrations/supported-models.mdx
  src/agents-api/agents_api/activities/task_steps/prompt_step.py
  src/agents-api/agents_api/autogen/Chat.py
  src/agents-api/agents_api/autogen/Tasks.py
  src/agents-api/agents_api/clients/litellm.py
  src/agents-api/agents_api/common/utils/llm_providers.py
  src/agents-api/agents_api/queries/tasks/get_task.py
  src/agents-api/agents_api/routers/sessions/auto_tools/render.py
  src/agents-api/agents_api/routers/sessions/legacy/render.py
  src/agents-api/tests/test_litellm_utils.py
  src/agents-api/tests/test_task_queries.py
  src/integrations-service/integrations/autogen/Chat.py
  src/integrations-service/integrations/autogen/Tasks.py
  src/llm-proxy/litellm-config.yaml
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/scripts/sync_model_docs.py
  src/typespec/entries/models.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5

#1534 feat(agents-api): add secrets to task definition
  changelog/dev/2025-07-31.md
  src/agents-api/agents_api/activities/task_steps/prompt_step.py
  src/agents-api/agents_api/common/protocol/tasks.py
  src/agents-api/agents_api/common/utils/secrets.py
  src/agents-api/tests/test_prepare_for_step.py
  src/agents-api/tests/test_prompt_step_auto_tools.py
  src/agents-api/tests/test_task_execution_workflow.py
  src/llm-proxy/litellm-config.yaml
Labels: Review effort 4/5, Possible security concern
