Repository julep-ai/julep, pull requests merged in 2025-06, with the labels that each got.

#1390 Remove unused msgpack import
  agents-api/agents_api/__init__.py
Labels: Review effort 1/5, codex

#1481 Update documentation to replace 'api_key' with 'brave_api_key'
  documentation/advanced/lifecycle.mdx
  documentation/advanced/types-of-task-steps.mdx
  documentation/concepts/tasks.mdx
  documentation/guides/getting-started/create-and-execute-julep-task.mdx
  documentation/sdks/nodejs/agents.mdx
  documentation/sdks/nodejs/tools-integration.mdx
  documentation/sdks/python/agents.mdx
  documentation/sdks/python/tools-integration.mdx
  documentation/tutorials/browser-use.mdx
  documentation/tutorials/trip-planning-tools.mdx
  documentation/tutorials/trip-planning-workflow.mdx
  documentation/tutorials/trip-planning.mdx
Labels: Review effort 2/5

#1485 feat(llm-proxy): Add gemini-2.5-pro-preview-06-05 model to litellm-config.yaml
  llm-proxy/litellm-config.yaml
Labels: Review effort 1/5

#1488 Claude PR Assistant workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: Review effort 2/5, Possible security concern

#1495 feat(llm-proxy): Add new groq model configurations
  llm-proxy/litellm-config.yaml
Labels: Review effort 2/5

#1496 feat: Add metadata field in chat requests
  agents-api/agents_api/autogen/Agents.py
  agents-api/agents_api/autogen/Chat.py
  agents-api/agents_api/autogen/Docs.py
  agents-api/agents_api/autogen/Executions.py
  agents-api/agents_api/autogen/Responses.py
  agents-api/agents_api/autogen/Tasks.py
  agents-api/agents_api/autogen/Tools.py
  agents-api/agents_api/routers/sessions/render.py
  agents-api/tests/test_chat_metadata.py
  documentation/advanced/chat.mdx
  documentation/advanced/system-templates.mdx
  documentation/concepts/agents.mdx
  documentation/concepts/sessions.mdx
  documentation/docs.json
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/chat/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1503 feat(agents-api): Add include_embeddings parameter to optimize document query bandwidth
  changelog/dev/2025-06-23.md
  changelog/dev/2025-06-25.md
  changelog/dev/2025-06-26.md
  src/agents-api/agents_api/autogen/Docs.py
  src/agents-api/agents_api/autogen/Sessions.py
  src/agents-api/agents_api/common/utils/get_doc_search.py
  src/agents-api/agents_api/queries/chat/gather_messages.py
  src/agents-api/agents_api/queries/docs/get_doc.py
  src/agents-api/agents_api/queries/docs/list_docs.py
  src/agents-api/agents_api/queries/docs/utils.py
  src/agents-api/agents_api/routers/docs/get_doc.py
  src/agents-api/agents_api/routers/docs/list_docs.py
  src/agents-api/agents_api/routers/docs/search_docs.py
  src/agents-api/tests/test_docs_queries.py
  src/agents-api/tests/test_get_doc_search.py
  src/integrations-service/integrations/autogen/Chat.py
  src/integrations-service/integrations/autogen/Docs.py
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/scripts/generate_openapi_code.sh
  src/typespec/docs/endpoints.tsp
  src/typespec/docs/models.tsp
  src/typespec/sessions/models.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1510 dev -> main (Jun 30th)
  .github/README-CN.md
  .github/README-FR.md
  .github/README-JA.md
  README.md
  documentation/FAQ.mdx
  documentation/docs.json
  documentation/integrations/assets/Algolia_logo_full_blue.svg
  documentation/integrations/assets/ArXiv_logo_2022.svg.png
  documentation/integrations/assets/Brave_logo.svg.png
  documentation/integrations/assets/Cloudinary_logo.svg.png
  documentation/integrations/assets/FFmpeg-Logo.svg
  documentation/integrations/assets/OWM.png
  documentation/integrations/assets/Playwright_Logo.svg.png
  documentation/integrations/assets/email.png
  documentation/integrations/assets/llamacloud-black.svg
  documentation/integrations/assets/logo-full.svg
  documentation/integrations/assets/pngimg.com - wikipedia_PNG30.png
  documentation/integrations/assets/spider-logo-github-dark.png
  documentation/integrations/assets/unstructured-color.png
  documentation/integrations/supported-integrations.mdx
  documentation/introduction/install.mdx
  documentation/snippets/integrations-slider.jsx
  documentation/style.css
  src/agents-api/agents_api/queries/tools/create_tools.py
Labels: Review effort 3/5
