Repository julep-ai/julep, pull requests merged in 2025-09, with the labels that each got.

#1553 chore: add sonar models to litellm config
  src/llm-proxy/litellm-config.yaml
Labels: Review effort 1/5

#1560 dev -> main (Sep 4th)
  src/integrations-service/integrations/models/execution.py
  src/integrations-service/integrations/utils/integrations/unstructured.py
  src/integrations-service/pyproject.toml
  src/integrations-service/uv.lock
Labels: Review effort 2/5

#1561 F/google sheets integration
  src/agents-api/agents_api/autogen/Tools.py
  src/integrations-service/docker-compose.yml
  src/integrations-service/integrations/autogen/Tools.py
  src/integrations-service/integrations/env.py
  src/integrations-service/integrations/models/__init__.py
  src/integrations-service/integrations/models/execution.py
  src/integrations-service/integrations/models/google_sheets.py
  src/integrations-service/integrations/providers.py
  src/integrations-service/integrations/utils/integrations/google_sheets.py
  src/integrations-service/pyproject.toml
  src/integrations-service/uv.lock
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/typespec/tools/google_sheets.tsp
  src/typespec/tools/main.tsp
  src/typespec/tools/models.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5, Possible security concern

#1564 Add Claude Code GitHub Workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: Review effort 2/5, Possible security concern

#1562 chore: remove unnecessary MCP example files and documentation
  .gitignore
  documentation/docs.json
  documentation/integrations/extensibility/mcp.mdx
  documentation/integrations/supported-integrations.mdx
  src/agents-api/agents_api/activities/execute_integration.py
  src/agents-api/agents_api/autogen/Tools.py
  src/agents-api/agents_api/common/utils/tool_runner.py
  src/integrations-service/AGENTS.md
  src/integrations-service/integrations/autogen/Tools.py
  src/integrations-service/integrations/models/__init__.py
  src/integrations-service/integrations/models/execution.py
  src/integrations-service/integrations/models/mcp.py
  src/integrations-service/integrations/providers.py
  src/integrations-service/integrations/routers/integrations/get_integration_tool.py
  src/integrations-service/integrations/utils/integrations/mcp.py
  src/integrations-service/pyproject.toml
  src/integrations-service/tests/test_mcp.py
  src/integrations-service/tests/test_mcp_sse_server.py
  src/integrations-service/tests/working_mcp_sse_server.py
  src/integrations-service/uv.lock
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/typespec/tools/main.tsp
  src/typespec/tools/mcp.tsp
  src/typespec/tools/models.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5, Possible security concern

#1569 F/mcp integration
  .gitignore
  documentation/docs.json
  documentation/integrations/extensibility/mcp.mdx
  documentation/integrations/supported-integrations.mdx
  src/agents-api/agents_api/activities/execute_integration.py
  src/agents-api/agents_api/autogen/Tools.py
  src/agents-api/agents_api/common/utils/tool_runner.py
  src/integrations-service/AGENTS.md
  src/integrations-service/integrations/autogen/Tools.py
  src/integrations-service/integrations/models/__init__.py
  src/integrations-service/integrations/models/execution.py
  src/integrations-service/integrations/models/mcp.py
  src/integrations-service/integrations/providers.py
  src/integrations-service/integrations/routers/integrations/get_integration_tool.py
  src/integrations-service/integrations/utils/integrations/mcp.py
  src/integrations-service/pyproject.toml
  src/integrations-service/tests/test_mcp.py
  src/integrations-service/tests/test_mcp_sse_server.py
  src/integrations-service/tests/working_mcp_sse_server.py
  src/integrations-service/uv.lock
  src/schemas/create_agent_request.json
  src/schemas/create_task_request.json
  src/typespec/tools/main.tsp
  src/typespec/tools/mcp.tsp
  src/typespec/tools/models.tsp
  src/typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5, Possible security concern

#1571 fix(agents-api): update model validation import path in tests to common utils
  src/agents-api/tests/fixtures.py
  src/agents-api/tests/test_model_validation.py
Labels: Review effort 1/5
