Repository julep-ai/julep, pull requests merged in 2025-01, with the labels that each got.

#1004 chore: Remove non-relevant tests
  agents-api/tests/test_activities.py
Labels: Review effort [1-5]: 1

#1005 feat(agents-api): add session routes tests
  agents-api/tests/test_session_routes.py
  agents-api/tests/test_sessions.py
Labels: Review effort [1-5]: 2

#1008 fix(agents-api,memory-store): Fix docs tests and related migration
  agents-api/agents_api/queries/docs/get_doc.py
  agents-api/agents_api/queries/docs/list_docs.py
  agents-api/agents_api/queries/docs/utils.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_docs_queries.py
  agents-api/tests/test_docs_routes.py
  agents-api/tests/utils.py
  memory-store/migrations/000018_doc_search.up.sql
Labels: Review effort [1-5]: 3

#1009 fix(agents-api): fix some ``test_execution_workflow`` tests
  agents-api/agents_api/activities/task_steps/prompt_step.py
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/queries/tasks/get_task.py
  agents-api/agents_api/routers/tasks/create_task_execution.py
  agents-api/tests/test_execution_workflow.py
Labels: Review effort [1-5]: 2

#1011 fix(agents-api,memory-store): Fix docs tests and some migrations
  agents-api/agents_api/queries/docs/get_doc.py
  agents-api/agents_api/queries/docs/list_docs.py
  agents-api/agents_api/queries/executions/create_execution_transition.py
  agents-api/agents_api/queries/utils.py
  agents-api/agents_api/routers/docs/search_docs.py
  agents-api/pyproject.toml
  agents-api/tests/fixtures.py
  agents-api/tests/test_docs_queries.py
  agents-api/tests/test_docs_routes.py
  agents-api/uv.lock
  memory-store/migrations/000012_transitions.up.sql
  memory-store/migrations/000013_executions_continuous_view.up.sql
  memory-store/migrations/000018_doc_search.up.sql
Labels: Review effort [1-5]: 3

#1012 fix(agents-api): Fix sessions `updated_at` precision issue
  agents-api/agents_api/activities/execute_system.py
  agents-api/agents_api/models/chat/prepare_chat_context.py
  agents-api/agents_api/models/session/get_session.py
  agents-api/agents_api/models/session/prepare_session_data.py
  agents-api/agents_api/models/session/update_session.py
Labels: Review effort [1-5]: 2

#1016 X/misc fixes
  agents-api/agents_api/app.py
  agents-api/agents_api/queries/chat/gather_messages.py
  agents-api/agents_api/queries/docs/search_docs_by_embedding.py
  agents-api/agents_api/queries/utils.py
  agents-api/agents_api/routers/docs/search_docs.py
  memory-store/migrations/000004_agents.up.sql
  memory-store/migrations/000015_entries.up.sql
Labels: Review effort [1-5]: 3

#1018 fix(agents-api): Fix timestamp type in entries
  agents-api/agents_api/autogen/Entries.py
  agents-api/agents_api/autogen/openapi_model.py
  agents-api/agents_api/queries/entries/create_entries.py
  integrations-service/integrations/autogen/Entries.py
  typespec/entries/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 2

#1020 D/cookbooks: Added new cookbooks
  agents-api/notebooks/01-revise-entities.ipynb
  agents-api/notebooks/02-trim-messages.ipynb
  agents-api/notebooks/03-summarise.ipynb
  agents-api/notebooks/RecSum-experiments.ipynb
  agents-api/notebooks/test-chat.json
  agents-api/pyproject.toml
  agents-api/tests/test_docs_queries.py
  cookbooks/08_customer_support_chatbot.ipynb
  cookbooks/09_companion_agent.ipynb
  cookbooks/README.md
  memory-store/README.md
Labels: Review effort [1-5]: 4

#1021 chore: toml fix for litellm
  agents-api/pyproject.toml
  agents-api/uv.lock
Labels: Review effort [1-5]: 1

#1023 fix(agents-api, memory-store): Add migration for delete cascade + search docs fixes
  agents-api/agents_api/autogen/Docs.py
  agents-api/agents_api/queries/docs/get_doc.py
  agents-api/agents_api/queries/docs/list_docs.py
  agents-api/agents_api/queries/docs/search_docs_by_embedding.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  integrations-service/integrations/autogen/Docs.py
  memory-store/migrations/000020_executions_task_cascade.down.sql
  memory-store/migrations/000020_executions_task_cascade.up.sql
  typespec/docs/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 3

#1025 chore: litellm upstream version
  llm-proxy/docker-compose.yml
Labels: Review effort [1-5]: 1

#1026 X/migration fix: Fixed migrations and docs search route
  agents-api/agents_api/queries/docs/search_docs_by_embedding.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  agents-api/tests/test_docs_routes.py
  memory-store/migrations/000021_fix_toolname_contraint.down.sql
  memory-store/migrations/000021_fix_toolname_contraint.up.sql
Labels: Review effort [1-5]: 2

#1028 feat: Add temporal API key
  agents-api/agents_api/clients/temporal.py
  agents-api/agents_api/env.py
  agents-api/docker-compose.yml
Labels: Review effort [1-5]: 2

#1034 feat(llm-proxy): Add support for O1 & other LLMs
  llm-proxy/litellm-config.yaml
Labels: Review effort [1-5]: 2

#1035 fix(memory-store, agents-api): Fix distance and confidence values for vector search
  agents-api/agents_api/queries/docs/search_docs_by_embedding.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  memory-store/migrations/000022_vector_search.down.sql
  memory-store/migrations/000022_vector_search.up.sql
Labels: Review effort [1-5]: 4

#1036 docs(mintlify): Add task walkthrough & other misc improvements
  documentation/building-blocks/agents/creating-agents.mdx
  documentation/getting-started/examples.mdx
  documentation/getting-started/julep-task-walkthrough.mdx
  documentation/mint.json
  documentation/tools/available-integrations.mdx
  documentation/tools/built-in-tools.mdx
  documentation/tools/integration-types.mdx
Labels: Review effort [1-5]: 2

#1038 hotfix(agents-api): Fixes for connection pool getting exhausted
  agents-api/.gitignore
  agents-api/agents_api/activities/container.py
  agents-api/agents_api/activities/execute_integration.py
  agents-api/agents_api/activities/execute_system.py
  agents-api/agents_api/activities/task_steps/pg_query_step.py
  agents-api/agents_api/activities/task_steps/transition_step.py
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/app.py
  agents-api/agents_api/clients/pg.py
  agents-api/agents_api/env.py
  agents-api/agents_api/routers/docs/create_doc.py
  agents-api/agents_api/routers/docs/search_docs.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/agents_api/worker/__main__.py
  memory-store/docker-compose.yml
Labels: Review effort [1-5]: 3

#1039 fix(memory-store): Remove bad indices
  memory-store/migrations/000012_transitions.up.sql
Labels: Review effort [1-5]: 2

#1041 hotfix(agents-api): fix in docs routes
  README-CN.md
  README-FR.md
  README-JA.md
  README.md
  agents-api/agents_api/routers/docs/create_doc.py
  agents-api/agents_api/routers/docs/search_docs.py
Labels: Review effort [1-5]: 2

#1046 fix(memory-store): fix vector search function
  agents-api/agents_api/autogen/Docs.py
  integrations-service/integrations/autogen/Docs.py
  memory-store/migrations/000022_vector_search.up.sql
  typespec/docs/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 3

#1048 fix(agents-api): enable agent tools endpoints
  agents-api/agents_api/routers/agents/__init__.py
  agents-api/agents_api/routers/agents/create_agent_tool.py
Labels: Review effort [1-5]: 1

#1050 hotfix: switch query table to transitions
  agents-api/agents_api/queries/executions/get_paused_execution_token.py
Labels: Review effort [1-5]: 1

#1051 feat(llm-proxy): Support for `l3.1-euryale-70b`
  llm-proxy/litellm-config.yaml
Labels: Review effort [1-5]: 1

#1053 chore(agents-memory-store): Increase strings lengths constraints
  memory-store/migrations/000023_update_strings_length_constraints.down.sql
  memory-store/migrations/000023_update_strings_length_constraints.up.sql
Labels: Review effort [1-5]: 2

#1054 dev -> main
  llm-proxy/litellm-config.yaml
  memory-store/migrations/000023_update_strings_length_constraints.down.sql
  memory-store/migrations/000023_update_strings_length_constraints.up.sql
Labels: Review effort [1-5]: 1

#1056 fix: Patch instructions and canonical name
  agents-api/agents_api/queries/agents/patch_agent.py
Labels: Review effort [1-5]: 2

#1057 fix: Patch instructions and canonical name
  agents-api/agents_api/queries/agents/patch_agent.py
Labels: Review effort [1-5]: 2

#1058 dev -> main
  agents-api/agents_api/queries/agents/patch_agent.py
Labels: Review effort [1-5]: 2

#1055 fix(agents-api): Configure spacy for postgresql
  agents-api/agents_api/common/nlp.py
  agents-api/agents_api/queries/docs/search_docs_by_text.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  agents-api/tests/test_docs_queries.py
  agents-api/tests/test_nlp_utilities.py
Labels: Review effort [1-5]: 3

#1045 fix(agents-api): init nlp pipeline text-search
  agents-api/agents_api/common/nlp.py
  agents-api/agents_api/queries/docs/search_docs_by_text.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_docs_queries.py
  agents-api/tests/test_nlp_utilities.py
  agents-api/tests/utils.py
Labels: Review effort [1-5]: 4

#1033 F/bb sdk v1.0: Updating the BrowserBase SDK from v0.x to v1.x
  agents-api/agents_api/autogen/Tools.py
  agents-api/docker-compose.yml
  cookbooks/06-browser-use.ipynb
  integrations-service/integrations/autogen/Tools.py
  integrations-service/integrations/models/__init__.py
  integrations-service/integrations/models/browserbase.py
  integrations-service/integrations/models/execution.py
  integrations-service/integrations/providers.py
  integrations-service/integrations/utils/integrations/browserbase.py
  integrations-service/pyproject.toml
  integrations-service/uv.lock
  typespec/tools/browserbase/sessions.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 4

#1059 fix(agents-api): Fix confidence range in recall_options
  agents-api/agents_api/autogen/Sessions.py
  integrations-service/integrations/autogen/Sessions.py
  typespec/sessions/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 1

#1062 fix(memory-store): add a migration to fix duplication issue in hybrid…
  memory-store/migrations/000024_hybrid_search.down.sql
  memory-store/migrations/000024_hybrid_search.up.sql
Labels: Review effort [1-5]: 4

#1061 dev -> main
  agents-api/agents_api/autogen/Sessions.py
  agents-api/agents_api/autogen/Tools.py
  agents-api/agents_api/common/nlp.py
  agents-api/agents_api/queries/docs/search_docs_by_text.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  agents-api/docker-compose.yml
  agents-api/tests/fixtures.py
  agents-api/tests/test_docs_queries.py
  agents-api/tests/test_nlp_utilities.py
  agents-api/tests/utils.py
  cookbooks/06-browser-use.ipynb
  integrations-service/integrations/autogen/Sessions.py
  integrations-service/integrations/autogen/Tools.py
  integrations-service/integrations/models/__init__.py
  integrations-service/integrations/models/browserbase.py
  integrations-service/integrations/models/execution.py
  integrations-service/integrations/providers.py
  integrations-service/integrations/utils/integrations/browserbase.py
  integrations-service/pyproject.toml
  integrations-service/uv.lock
  llm-proxy/litellm-config.yaml
  memory-store/migrations/000024_hybrid_search.down.sql
  memory-store/migrations/000024_hybrid_search.up.sql
  typespec/sessions/models.tsp
  typespec/tools/browserbase/sessions.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 4

#1064 docs(integration):Integrations section
  documentation/docs/advanced/agentic-patterns.mdx
  documentation/docs/advanced/architecture-deep-dive.mdx
  documentation/docs/advanced/execution-lifecycle.mdx
  documentation/docs/advanced/files.mdx
  documentation/docs/advanced/multi-agent-multi-user-sessions.mdx
  documentation/docs/advanced/types-of-task-steps.mdx
  documentation/docs/concepts/agents.mdx
  documentation/docs/concepts/docs.mdx
  documentation/docs/concepts/sessions.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/docs/concepts/tools.mdx
  documentation/docs/concepts/users.mdx
  documentation/docs/integrations/communication/email.mdx
  documentation/docs/integrations/data-services/arxiv.mdx
  documentation/docs/integrations/data-services/weather.mdx
  documentation/docs/integrations/document-processing/llama-parse.mdx
  documentation/docs/integrations/media-processing/cloudinary.mdx
  documentation/docs/integrations/media-processing/ffmpeg.mdx
  documentation/docs/integrations/search-research/arxiv.mdx
  documentation/docs/integrations/search-research/brave-search.mdx
  documentation/docs/integrations/search-research/wikipedia.mdx
  documentation/docs/integrations/search/brave-search.mdx
  documentation/docs/integrations/search/wikipedia.mdx
  documentation/docs/integrations/supported-models.mdx
  documentation/docs/integrations/web-browser/browser-base.mdx
  documentation/docs/integrations/web-browser/spider.mdx
  documentation/docs/integrations/web/browserbase.mdx
  documentation/docs/integrations/web/spider.mdx
  documentation/docs/introduction/create-agent.mdx
  documentation/docs/introduction/explore-features.mdx
  documentation/docs/introduction/run-task.mdx
  documentation/docs/introduction/try-it-out.mdx
  documentation/docs/introduction/what-is-julep.mdx
  documentation/docs/tutorials/browser-use.mdx
  documentation/docs/tutorials/crawling-web-pages-with-rag.mdx
  documentation/docs/tutorials/multi-agent-research.mdx
  documentation/docs/tutorials/video-processing.mdx
  documentation/mint.json
Labels: Review effort [1-5]: 2

#1067 chore(docs): Add Tutorials
  documentation/docs/tutorials/browser-use.mdx
  documentation/docs/tutorials/crawling-web-pages-with-rag.mdx
  documentation/docs/tutorials/multi-agent-research.mdx
  documentation/docs/tutorials/trip-planning.mdx
  documentation/docs/tutorials/video-processing.mdx
  documentation/mint.json
Labels: Review effort [1-5]: 4

#1069 fix(agents-api): add model validation for agent and chat endpoints
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/routers/agents/create_agent.py
  agents-api/agents_api/routers/agents/create_or_update_agent.py
  agents-api/agents_api/routers/agents/patch_agent.py
  agents-api/agents_api/routers/agents/update_agent.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/agents_api/routers/utils/model_validation.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_model_validation.py
Labels: Review effort [1-5]: 2

#1070 wip: get started + advance topics
  documentation/docs/advanced/architecture-deep-dive.mdx
  documentation/docs/advanced/chat.mdx
  documentation/docs/advanced/execution-lifecycle.mdx
  documentation/docs/advanced/multi-agent-multi-user-sessions.mdx
  documentation/docs/advanced/python-expression.mdx
  documentation/docs/advanced/types-of-task-steps.mdx
  documentation/docs/concepts/execution.mdx
  documentation/docs/integrations/communication_data/email.mdx
  documentation/docs/integrations/communication_data/weather.mdx
  documentation/docs/integrations/media_file_processing/cloudinary.mdx
  documentation/docs/integrations/media_file_processing/ffmpeg.mdx
  documentation/docs/integrations/media_file_processing/llama-parse.mdx
  documentation/docs/integrations/search_research/arxiv.mdx
  documentation/docs/integrations/search_research/brave-search.mdx
  documentation/docs/integrations/search_research/wikipedia.mdx
  documentation/docs/integrations/supported-models.mdx
  documentation/docs/integrations/web_browser_automation/browserbase.mdx
  documentation/docs/integrations/web_browser_automation/remote_browser.mdx
  documentation/docs/integrations/web_browser_automation/spider.mdx
  documentation/docs/introduction/create-agent.mdx
  documentation/docs/introduction/explore-features.mdx
  documentation/docs/introduction/install.mdx
  documentation/docs/introduction/run-task.mdx
  documentation/docs/introduction/try-it-out.mdx
  documentation/docs/introduction/try_it_out.mdx
  documentation/docs/introduction/what-is-julep.mdx
  documentation/docs/introduction/what_is_julep.mdx
  documentation/getting-started/examples.mdx
  documentation/getting-started/julep-task-walkthrough.mdx
  documentation/images/data-flow.png
  documentation/images/execution-lifecycle.png
  documentation/images/julep-architecture.png
  documentation/introduction/architecture-overview.mdx
  documentation/mint.json
  documentation/tools/available-integrations.mdx
  documentation/welcome.mdx
Labels: Review effort [1-5]: 4

#1071 fix(agents-api): developer_id constraint in prepare_chat_context
  agents-api/agents_api/queries/chat/prepare_chat_context.py
Labels: Review effort [1-5]: 2

#1072 doc(cookbooks): Add crawling & rag cookbook
  cookbooks/10-crawling-and-rag.ipynb
  cookbooks/README.md
Labels: Review effort [1-5]: 1

#1073 docs(advanced-topics): Add PyExp, Agentic Patterns & Files pages
  documentation/docs/advanced/agentic-patterns.mdx
  documentation/docs/advanced/files.mdx
  documentation/docs/advanced/python-expression.mdx
  documentation/docs/advanced/types-of-task-steps.mdx
Labels: Review effort [1-5]: 4

#1074 dev -> main
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/queries/chat/prepare_chat_context.py
  agents-api/agents_api/routers/agents/create_agent.py
  agents-api/agents_api/routers/agents/create_or_update_agent.py
  agents-api/agents_api/routers/agents/patch_agent.py
  agents-api/agents_api/routers/agents/update_agent.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/agents_api/routers/utils/model_validation.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_model_validation.py
  cookbooks/10-crawling-and-rag.ipynb
  cookbooks/README.md
Labels: Review effort [1-5]: 3

#1076 fix(agents-api): allow nested dictionaries in ``EvaluateStep`` and ``SetStep``
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/autogen/Tasks.py
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/routers/agents/create_agent.py
  agents-api/agents_api/routers/agents/create_or_update_agent.py
  agents-api/agents_api/routers/agents/patch_agent.py
  agents-api/agents_api/routers/agents/update_agent.py
  agents-api/agents_api/routers/utils/model_validation.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_simple_eval_dict.py
  agents-api/tests/test_workflow_routes.py
  typespec/tasks/steps.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 3

#1077 docs(concepts): Add core-concepts pages (Sessions, Executions, Users & Docs)
  documentation/docs/concepts/docs.mdx
  documentation/docs/concepts/execution.mdx
  documentation/docs/concepts/sessions.mdx
  documentation/docs/concepts/users.mdx
Labels: Review effort [1-5]: 4

#1079 feat(litellm-proxy): Add support for openai's o1 model
  llm-proxy/litellm-config.yaml
Labels: Review effort [1-5]: 1

#1085 docs: minor fix for tools
  documentation/docs/concepts/tools.mdx
Labels: Review effort [1-5]: 1

#1087 chore(agents-api): completely remove ``previous_inputs`` + misc
  agents-api/agents_api/clients/temporal.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/tests/test_task_execution_workflow.py
Labels: Review effort [1-5]: 3

#1088 docs: Misc fixes
  documentation/docs/concepts/agents.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/docs/integrations/supported-integrations.mdx
  documentation/docs/tutorials/browser-use.mdx
  documentation/docs/tutorials/crawling-web-pages-with-rag.mdx
  documentation/docs/tutorials/trip-planning.mdx
  documentation/docs/tutorials/video-processing.mdx
  documentation/mint.json
Labels: Review effort [1-5]: 1

#1090 documentation: misc improvements
  documentation/docs/advanced/lifecycle.mdx
  documentation/docs/advanced/localsetup.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/docs/concepts/tools.mdx
  documentation/docs/integrations/supported-integrations.mdx
  documentation/docs/introduction/install.mdx
  documentation/docs/introduction/julep.mdx
  documentation/images/lifecycle.svg
  documentation/images/relationship.svg
  documentation/mint.json
Labels: Review effort [1-5]: 2

#1091 docs: minor fix
  documentation/docs/advanced/localsetup.mdx
Labels: Review effort [1-5]: 1

#1092 chore(docs): added error step
  documentation/docs/advanced/types-of-task-steps.mdx
  documentation/docs/concepts/agents.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/docs/concepts/tools.mdx
  documentation/docs/introduction/quickstart.mdx
Labels: Review effort [1-5]: 2

#1093 fix(agents-api): fix unwrap in prompt step
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/tests/test_task_execution_workflow.py
Labels: Review effort [1-5]: 2

#1068 fix(agents-api): Fix blob-store interceptor implementation
  agents-api/agents_api/activities/sync_items_remote.py
  agents-api/agents_api/activities/task_steps/evaluate_step.py
  agents-api/agents_api/app.py
  agents-api/agents_api/clients/async_s3.py
  agents-api/agents_api/clients/sync_s3.py
  agents-api/agents_api/clients/temporal.py
  agents-api/agents_api/common/interceptors.py
  agents-api/agents_api/common/protocol/models.py
  agents-api/agents_api/common/protocol/remote.py
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/env.py
  agents-api/agents_api/worker/codec.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/agents_api/workflows/task_execution/transition.py
Labels: Review effort [1-5]: 4

#1097 feat(cli): Add sync command
  cli/julep_cli/__init__.py
  cli/julep_cli/auth.py
  cli/julep_cli/models.py
  cli/julep_cli/sync.py
  cli/julep_cli/utils.py
Labels: Review effort [1-5]: 4

#1099 fix(agents-api): fix docs embedding fixture
  agents-api/tests/fixtures.py
Labels: Review effort [1-5]: 2

#1098 fix(agents-api): fixed the docs metadata filter query + tests
  agents-api/agents_api/queries/docs/list_docs.py
  agents-api/agents_api/queries/executions/create_execution_transition.py
  agents-api/agents_api/queries/utils.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_docs_queries.py
  documentation/docs/integrations/supported-models.mdx
Labels: Review effort [1-5]: 2

#1100 feat(cli): Add import agent command
  cli/julep_cli/__init__.py
  cli/julep_cli/app.py
  cli/julep_cli/importt.py
  cli/julep_cli/utils.py
Labels: Review effort [1-5]: 3

#1102 fix(agents-api): fix inputs array fetched from the transitions table
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/routers/docs/search_docs.py
  agents-api/agents_api/routers/sessions/chat.py
Labels: Review effort [1-5]: 2

#1103 Add connection pool placeholder
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/queries/docs/create_doc.py
  agents-api/agents_api/routers/docs/create_doc.py
  agents-api/agents_api/routers/docs/search_docs.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/tests/fixtures.py
Labels: Review effort [1-5]: 2

#1104 dev -> main
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/queries/docs/create_doc.py
  agents-api/agents_api/routers/docs/create_doc.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_execution_workflow.py
Labels: Review effort [1-5]: 2

#1105 feat(documentation): added posthog analytics to docs
  documentation/mint.json
Labels: Review effort [1-5]: 1

#1108 feat(cli): Add rich text for cli
  cli/julep_cli/agents.py
  cli/julep_cli/chat.py
  cli/julep_cli/executions.py
  cli/julep_cli/importt.py
  cli/julep_cli/init.py
  cli/julep_cli/logs.py
  cli/julep_cli/ls.py
  cli/julep_cli/sync.py
  cli/julep_cli/tasks.py
  cli/julep_cli/tools.py
  cli/julep_cli/utils.py
Labels: Review effort [1-5]: 4

#1109 chore(cli): refactored cli for pip build
  cli/julep_cli/__main__.py
  cli/pyproject.toml
  cli/src/julep_cli/__init__.py
  cli/src/julep_cli/__main__.py
  cli/src/julep_cli/agents.py
  cli/src/julep_cli/app.py
  cli/src/julep_cli/auth.py
  cli/src/julep_cli/chat.py
  cli/src/julep_cli/executions.py
  cli/src/julep_cli/importt.py
  cli/src/julep_cli/init.py
  cli/src/julep_cli/logs.py
  cli/src/julep_cli/ls.py
  cli/src/julep_cli/models.py
  cli/src/julep_cli/run.py
  cli/src/julep_cli/sync.py
  cli/src/julep_cli/tasks.py
  cli/src/julep_cli/tools.py
  cli/src/julep_cli/utils.py
Labels: Review effort [1-5]: 4

#1112 chore(workflow): environment variable fix for changelog
  .github/workflows/generate-changelog.yml
Labels: Review effort [1-5]: 2

#1107 feat(agents-api): add prefix to evaluate python expressions
  agents-api/agents_api/activities/task_steps/__init__.py
  agents-api/agents_api/activities/task_steps/base_evaluate.py
  agents-api/agents_api/activities/task_steps/evaluate_step.py
  agents-api/agents_api/activities/task_steps/for_each_step.py
  agents-api/agents_api/activities/task_steps/if_else_step.py
  agents-api/agents_api/activities/task_steps/log_step.py
  agents-api/agents_api/activities/task_steps/map_reduce_step.py
  agents-api/agents_api/activities/task_steps/prompt_step.py
  agents-api/agents_api/activities/task_steps/return_step.py
  agents-api/agents_api/activities/task_steps/set_value_step.py
  agents-api/agents_api/activities/task_steps/switch_step.py
  agents-api/agents_api/activities/task_steps/tool_call_step.py
  agents-api/agents_api/activities/task_steps/wait_for_input_step.py
  agents-api/agents_api/activities/task_steps/yield_step.py
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/tests/test_base_evaluate.py
  agents-api/tests/test_simple_eval_dict.py
  agents-api/tests/test_task_execution_workflow.py
Labels: Review effort [1-5]: 3
