Repository julep-ai/julep, pull requests merged in 2025-04, with the labels that each got.

#1291 docs: upgraded Mintlify to docs.json + fixed broken links + changed d…
  documentation/docs.json
  documentation/docs/advanced/chat.mdx
  documentation/docs/advanced/lifecycle.mdx
  documentation/docs/advanced/python-expression.mdx
  documentation/docs/advanced/render.mdx
  documentation/docs/concepts/agents.mdx
  documentation/docs/concepts/execution.mdx
  documentation/docs/concepts/tools.mdx
  documentation/docs/integrations/contributing-integrations.mdx
  documentation/docs/julepcli/introduction.mdx
  documentation/mint.json
  documentation/openapi.yaml
  documentation/responses/quickstart.mdx
Labels: Review effort 2/5

#1301 fix(agents-api): disable task validation temporarily
  agents-api/agents_api/common/utils/task_validation.py
Labels: Review effort 1/5

#1302 fix(agents-api): improve expression validation for comprehensions and unsupported features
  agents-api/agents_api/common/utils/task_validation.py
  agents-api/tests/test_task_validation.py
Labels: Review effort 2/5

#1307 chore: Replace Postgraphile with Hasura for GraphQL service
  .env.example
  docker-compose.yml
  graphql/docker-compose.yml
  hasura/docker-compose.yml
Labels: Review effort 2/5

#1300 fix: Reference not found error re-raise
  agents-api/agents_api/common/utils/db_exceptions.py
  agents-api/tests/test_docs_queries.py
Labels: Review effort 2/5

#1310 chore(gateway): Expose GraphQL API
  .env.example
  gateway/docker-compose.yml
  gateway/entrypoint.sh
  gateway/traefik.yml.template
  hasura/docker-compose.yml
Labels: Review effort 2/5

#1305 feat: Add a flag to optionally include API response content
  agents-api/agents_api/activities/execute_api_call.py
  agents-api/agents_api/autogen/Tools.py
  agents-api/pyproject.toml
  agents-api/tests/test_task_execution_workflow.py
  agents-api/uv.lock
  integrations-service/integrations/autogen/Tools.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/tools/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1303 refactor: Move query parameters validation to beartype
  agents-api/agents_api/common/exceptions/validation.py
  agents-api/agents_api/common/utils/db_exceptions.py
  agents-api/agents_api/common/utils/task_validation.py
  agents-api/agents_api/queries/agents/list_agents.py
  agents-api/agents_api/queries/docs/list_docs.py
  agents-api/agents_api/queries/entries/list_entries.py
  agents-api/agents_api/queries/executions/list_executions.py
  agents-api/agents_api/queries/files/list_files.py
  agents-api/agents_api/queries/tasks/list_tasks.py
  agents-api/agents_api/queries/users/list_users.py
  agents-api/agents_api/queries/utils.py
  agents-api/tests/test_agent_queries.py
  agents-api/tests/test_docs_queries.py
  agents-api/tests/test_entry_queries.py
  agents-api/tests/test_execution_queries.py
  agents-api/tests/test_files_queries.py
  agents-api/tests/test_task_queries.py
  agents-api/tests/test_user_queries.py
Labels: Review effort 3/5

#1311 chore(hasura): Add hasura metadata
  hasura/metadata/hasura_metadata_2025_04_07_16_21_57_118.json
Labels: Review effort 3/5

#1314 feat(litellm): Add support for Gemini 2.0 flash & 2.5 pro preview
  documentation/docs/integrations/supported-models.mdx
  llm-proxy/litellm-config.yaml
Labels: Review effort 1/5

#1313 chore(agents-api, integrations): add gunicorn workers envs
  agents-api/agents_api/env.py
  agents-api/docker-compose.yml
  agents-api/gunicorn_conf.py
  integrations-service/docker-compose.yml
  integrations-service/gunicorn_conf.py
  integrations-service/integrations/env.py
Labels: Review effort 2/5

#1315 fix(documentation): Fix wrong indentations in code blocks
  documentation/docs/concepts/docs.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/docs/concepts/tools.mdx
  documentation/docs/integrations/communicationdata/email.mdx
  documentation/docs/integrations/communicationdata/weather.mdx
  documentation/docs/integrations/mediafile/cloudinary.mdx
  documentation/docs/integrations/mediafile/ffmpeg.mdx
  documentation/docs/integrations/mediafile/llamaparse.mdx
  documentation/docs/integrations/mediafile/unstructured.mdx
  documentation/docs/integrations/search/algolia.mdx
  documentation/docs/integrations/search/arxiv.mdx
  documentation/docs/integrations/search/brave.mdx
  documentation/docs/integrations/search/wikipedia.mdx
  documentation/docs/integrations/webbrowser/browserbase.mdx
  documentation/docs/integrations/webbrowser/remote-browser.mdx
  documentation/docs/integrations/webbrowser/spider.mdx
  documentation/docs/julepcli/introduction.mdx
  documentation/docs/tutorials/browser-use.mdx
  documentation/docs/tutorials/rag-chatbot.mdx
  documentation/docs/tutorials/trip-planning.mdx
  documentation/docs/tutorials/video-processing.mdx
Labels: Review effort 1/5

#1316 feat(agents-api): add usage tracking + usage table
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/common/utils/usage.py
  agents-api/agents_api/queries/__init__.py
  agents-api/agents_api/queries/usage/__init__.py
  agents-api/agents_api/queries/usage/create_usage_record.py
  agents-api/tests/test_usage_tracking.py
  memory-store/migrations/000036_usage.down.sql
  memory-store/migrations/000036_usage.up.sql
Labels: Review effort 3/5

#1320 fix(cookbooks): User dictionary style access for 'from'
  cookbooks/00-Devfest-Email-Assistant.ipynb
Labels: Review effort 1/5

#1322 fix(cookbooks, docs): update string formatting and improve evaluation…
  cookbooks/06-browser-use.ipynb
  documentation/tutorials/browser-use.mdx
Labels: Review effort 2/5

#1318 feat(agents-api): enhance health check endpoint to monitor multiple s…
  agents-api/agents_api/common/utils/checks.py
  agents-api/agents_api/routers/healthz/check_health.py
Labels: Review effort 2/5

#1324 fix(cookbooks): Fix regressed issues in cookbooks
  cookbooks/01-website-crawler.ipynb
  cookbooks/02-sarcastic-news-headline-generator.ipynb
  cookbooks/03-trip-planning-assistant.ipynb
  cookbooks/05-video-processing-with-natural-language.ipynb
Labels: Review effort 2/5

#1328 fix(documentation): Add missing $ to expression
  documentation/advanced/python-expression.mdx
Labels: Review effort 1/5

#1325 feat(integrations-service): Add mailgun integration
  agents-api/agents_api/autogen/Tools.py
  integrations-service/docker-compose.yml
  integrations-service/integrations/autogen/Tools.py
  integrations-service/integrations/env.py
  integrations-service/integrations/models/__init__.py
  integrations-service/integrations/models/execution.py
  integrations-service/integrations/models/mailgun.py
  integrations-service/integrations/providers.py
  integrations-service/integrations/utils/integrations/mailgun.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/tools/mailgun.tsp
  typespec/tools/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1329 feat(agents-api): add list available models endpoint
  agents-api/agents_api/autogen/Agents.py
  agents-api/agents_api/routers/agents/__init__.py
  agents-api/agents_api/routers/agents/list_models.py
  integrations-service/integrations/autogen/Agents.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/agents/endpoints.tsp
  typespec/agents/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 2/5

#1332 fix(agents-api): fix fallback pricing
  agents-api/agents_api/queries/usage/create_usage_record.py
Labels: Review effort 1/5

#1333 feat(hasura): Add updated hasura metadata
  hasura/metadata/hasura_metadata_2025_04_24_14_57_23_154.json
Labels: Review effort 3/5

#1335 fix(memory-store): expose db port
  memory-store/docker-compose.yml
Labels: Review effort 1/5

#1330 fix(cookbooks): Fix regressed issues in cookbooks
  cookbooks/07-personalized-research-assistant.ipynb
Labels: Review effort 1/5

#1319 fix: Speed up search
  memory-store/migrations/000037_speed_up_search.down.sql
  memory-store/migrations/000037_speed_up_search.up.sql
Labels: Review effort 4/5

#1340 fix(agents-api): add pydantic model calulation to total_size function
  agents-api/agents_api/common/utils/memory.py
Labels: Review effort 2/5

#1341 fix(agents-api): remove doc_owners check from doc query
  agents-api/agents_api/queries/docs/delete_doc.py
Labels: Review effort 2/5

#1342 dev -> main (Apr 29)
  agents-api/agents_api/common/utils/memory.py
  agents-api/agents_api/queries/docs/delete_doc.py
  cookbooks/07-personalized-research-assistant.ipynb
  hasura/metadata/hasura_metadata_2025_04_24_14_57_23_154.json
  memory-store/docker-compose.yml
  memory-store/migrations/000037_speed_up_search.down.sql
  memory-store/migrations/000037_speed_up_search.up.sql
Labels: Review effort 3/5

#1343 fix(agents-api): various fixes for queries and endpoints
  agents-api/agents_api/autogen/Secrets.py
  agents-api/agents_api/common/utils/expressions.py
  agents-api/agents_api/queries/secrets/create.py
  agents-api/agents_api/queries/secrets/delete.py
  agents-api/agents_api/routers/secrets/create_secret.py
  agents-api/agents_api/routers/secrets/update_secret.py
  agents-api/docker-compose.yml
  integrations-service/integrations/autogen/Secrets.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/secrets/endpoints.tsp
  typespec/secrets/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5
