Repository julep-ai/julep, pull requests merged in 2025-03, with the labels that each got.

#1193 chore(agents-api): Misc improvements in humanize_text function
  agents-api/agents_api/activities/humanization_utils.py
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/workflows/task_execution/helpers.py
Labels: Review effort 3/5

#1201 feat(agents-api): render endpoint for debugging sessions
  .cursorignore
  .cursorindexignore
  agents-api/agents_api/autogen/Chat.py
  agents-api/agents_api/autogen/Sessions.py
  agents-api/agents_api/common/utils/template.py
  agents-api/agents_api/routers/sessions/__init__.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/agents_api/routers/sessions/render.py
  agents-api/tests/test_chat_routes.py
  documentation/docs/advanced/render.mdx
  documentation/mint.json
  integrations-service/integrations/autogen/Chat.py
  integrations-service/integrations/autogen/Sessions.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  scripts/generate_openapi_code.sh
  typespec/chat/endpoints.tsp
  typespec/chat/models.tsp
  typespec/main.tsp
  typespec/sessions/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5

#1198 feat(agents-api): add markdown_to_html and html_to_markdown utils
  agents-api/agents_api/activities/utils.py
  agents-api/pyproject.toml
  agents-api/tests/test_activities_utils.py
  agents-api/uv.lock
  documentation/docs/advanced/python-expression.mdx
Labels: Review effort 2/5

#1202 fix(agents-api): Add test for template merging issue
  agents-api/agents_api/queries/chat/prepare_chat_context.py
  agents-api/tests/test_chat_routes.py
Labels: Review effort 2/5

#1207 fix: Decompress chunks before altering tables
  memory-store/migrations/000027_add_postgraphile.down.sql
  memory-store/migrations/000027_add_postgraphile.up.sql
Labels: Review effort 2/5

#1210 feat(agents-api,migrations): Add trigram search to FTS
  agents-api/agents_api/common/nlp.py
  agents-api/agents_api/common/utils/get_doc_search.py
  agents-api/agents_api/queries/chat/gather_messages.py
  agents-api/agents_api/queries/docs/search_docs_by_text.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  agents-api/agents_api/routers/docs/search_docs.py
  agents-api/tests/test_get_doc_search.py
  agents-api/tests/test_nlp_utilities.py
  memory-store/migrations/000030_add_unaccent_search_config.down.sql
  memory-store/migrations/000030_add_unaccent_search_config.up.sql
  memory-store/migrations/000031_add_trigram_search.down.sql
  memory-store/migrations/000031_add_trigram_search.up.sql
Labels: Review effort 3/5

#1222 fix(agents-api): Update nlp.py to remove price from query
  agents-api/agents_api/common/nlp.py
Labels: Review effort 1/5

#1215 chore(agents-api): slice docs to top k in case docs len > limit
  agents-api/agents_api/common/utils/get_doc_search.py
  agents-api/agents_api/common/utils/mmr.py
  agents-api/agents_api/queries/chat/gather_messages.py
  agents-api/agents_api/routers/docs/search_docs.py
  agents-api/tests/test_get_doc_search.py
  agents-api/tests/test_mmr.py
Labels: Review effort 2/5

#1228 docs: added entelligence chat feature
  documentation/scripts/entelligence-chat.js
Labels: Review effort 2/5

#1224 feat(integrations): added unstructured and refactors
  agents-api/agents_api/autogen/Tools.py
  documentation/docs/integrations/media_file_processing/llama-parse.mdx
  documentation/docs/integrations/media_file_processing/unstructured.mdx
  documentation/docs/integrations/search_research/brave-search.mdx
  documentation/docs/integrations/supported-integrations.mdx
  documentation/mint.json
  integrations-service/docker-compose.yml
  integrations-service/integrations/autogen/Tools.py
  integrations-service/integrations/env.py
  integrations-service/integrations/models/__init__.py
  integrations-service/integrations/models/execution.py
  integrations-service/integrations/models/unstructured.py
  integrations-service/integrations/providers.py
  integrations-service/integrations/utils/integrations/arxiv.py
  integrations-service/integrations/utils/integrations/brave.py
  integrations-service/integrations/utils/integrations/cloudinary.py
  integrations-service/integrations/utils/integrations/ffmpeg.py
  integrations-service/integrations/utils/integrations/llama_parse.py
  integrations-service/integrations/utils/integrations/spider.py
  integrations-service/integrations/utils/integrations/unstructured.py
  integrations-service/integrations/utils/integrations/weather.py
  integrations-service/integrations/utils/integrations/wikipedia.py
  integrations-service/pyproject.toml
  integrations-service/uv.lock
  typespec/tools/brave.tsp
  typespec/tools/main.tsp
  typespec/tools/models.tsp
  typespec/tools/unstructured.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1235 feat(memory-store): add a new implementation for search_by_text function
  memory-store/migrations/000032_enhance_trigram_search.down.sql
  memory-store/migrations/000032_enhance_trigram_search.up.sql
Labels: Review effort 3/5

#1237 fix: remove idx_docs_search_covering index from search_by_text
  memory-store/migrations/000032_enhance_trigram_search.down.sql
  memory-store/migrations/000032_enhance_trigram_search.up.sql
Labels: Review effort 1/5

#1241 feat(agents-api): add logic to create_response endpoint
  agents-api/agents_api/autogen/Responses.py
  agents-api/agents_api/routers/responses/create_response.py
  agents-api/agents_api/routers/utils/model_converters.py
  typespec/responses/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1221 fix(agents-api): extract_json and db string sanitization
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/queries/utils.py
  agents-api/tests/test_activities_utils.py
  agents-api/tests/test_query_utils.py
Labels: Review effort 2/5

#1231 feat(integrations): added algolia search
  agents-api/agents_api/autogen/Tools.py
  documentation/docs/concepts/tools.mdx
  documentation/docs/integrations/communication_data/email.mdx
  documentation/docs/integrations/communication_data/weather.mdx
  documentation/docs/integrations/media_file_processing/cloudinary.mdx
  documentation/docs/integrations/media_file_processing/ffmpeg.mdx
  documentation/docs/integrations/media_file_processing/llama-parse.mdx
  documentation/docs/integrations/media_file_processing/unstructured.mdx
  documentation/docs/integrations/search_research/algolia.mdx
  documentation/docs/integrations/search_research/arxiv.mdx
  documentation/docs/integrations/search_research/brave-search.mdx
  documentation/docs/integrations/search_research/wikipedia.mdx
  documentation/docs/integrations/supported-integrations.mdx
  documentation/docs/integrations/web_browser_automation/browserbase.mdx
  documentation/docs/integrations/web_browser_automation/remote_browser.mdx
  documentation/docs/integrations/web_browser_automation/spider.mdx
  documentation/mint.json
  integrations-service/docker-compose.yml
  integrations-service/integrations/autogen/Tools.py
  integrations-service/integrations/env.py
  integrations-service/integrations/models/__init__.py
  integrations-service/integrations/models/algolia.py
  integrations-service/integrations/models/execution.py
  integrations-service/integrations/providers.py
  integrations-service/integrations/utils/integrations/algolia.py
  integrations-service/integrations/utils/integrations/llama_parse.py
  integrations-service/pyproject.toml
  integrations-service/uv.lock
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/tools/algolia.tsp
  typespec/tools/main.tsp
  typespec/tools/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1249 docs: misc refactors + improvs docs
  documentation/docs/concepts/tools.mdx
  documentation/docs/integrations/communicationdata/email.mdx
  documentation/docs/integrations/communicationdata/weather.mdx
  documentation/docs/integrations/mediafile/cloudinary.mdx
  documentation/docs/integrations/mediafile/ffmpeg.mdx
  documentation/docs/integrations/mediafile/llamaparse.mdx
  documentation/docs/integrations/mediafile/unstructured.mdx
  documentation/docs/integrations/search/algolia.mdx
  documentation/docs/integrations/search/arxiv.mdx
  documentation/docs/integrations/search/brave.mdx
  documentation/docs/integrations/search/wikipedia.mdx
  documentation/docs/integrations/supported-integrations.mdx
  documentation/docs/integrations/webbrowser/browserbase.mdx
  documentation/docs/integrations/webbrowser/remote-browser.mdx
  documentation/docs/integrations/webbrowser/spider.mdx
  documentation/docs/introduction/install.mdx
  documentation/docs/tutorials/browser-use.mdx
  documentation/docs/tutorials/rag-chatbot.mdx
  documentation/docs/tutorials/trip-planning.mdx
  documentation/docs/tutorials/video-processing.mdx
  documentation/mint.json
Labels: Review effort 2/5

#1251 docs: integrations setup fixes
  documentation/docs/integrations/communicationdata/email.mdx
  documentation/docs/integrations/communicationdata/weather.mdx
  documentation/docs/integrations/mediafile/cloudinary.mdx
  documentation/docs/integrations/mediafile/llamaparse.mdx
  documentation/docs/integrations/mediafile/unstructured.mdx
  documentation/docs/integrations/search/algolia.mdx
  documentation/docs/integrations/search/brave.mdx
  documentation/docs/integrations/webbrowser/browserbase.mdx
  documentation/docs/integrations/webbrowser/remote-browser.mdx
  documentation/docs/integrations/webbrowser/spider.mdx
Labels: Review effort 1/5

#1255 docs: Tutorial create agent fix
  documentation/docs/tutorials/browser-use.mdx
  documentation/docs/tutorials/rag-chatbot.mdx
  documentation/docs/tutorials/trip-planning.mdx
  documentation/docs/tutorials/video-processing.mdx
Labels: Review effort 1/5

#1245 feat(agents-api): fork old session if provided id
  agents-api/agents_api/autogen/Chat.py
  agents-api/agents_api/autogen/openapi_model.py
  agents-api/agents_api/queries/entries/__init__.py
  agents-api/agents_api/routers/responses/__init__.py
  agents-api/agents_api/routers/responses/get_response.py
  agents-api/agents_api/routers/utils/model_converters.py
  integrations-service/integrations/autogen/Chat.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/chat/models.tsp
  typespec/responses/endpoints.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1260 doc: Add CLAUDE.md files to help LLMs understand the codebase quickly
  .cursorignore
  .cursorindexignore
  .cursorrules
  CLAUDE.md
  agents-api/CLAUDE.md
  agents-api/agents_api/activities/CLAUDE.md
  agents-api/agents_api/autogen/CLAUDE.md
  agents-api/agents_api/clients/CLAUDE.md
  agents-api/agents_api/common/CLAUDE.md
  agents-api/agents_api/queries/CLAUDE.md
  agents-api/agents_api/routers/CLAUDE.md
  agents-api/agents_api/worker/CLAUDE.md
  agents-api/agents_api/workflows/CLAUDE.md
  cli/CLAUDE.md
  documentation/CLAUDE.md
  integrations-service/CLAUDE.md
  memory-store/CLAUDE.md
  typespec/CLAUDE.md
Labels: Review effort 2/5

#1258 fix: repair latest_transitions continuous aggregate view
  agents-api/agents_api/autogen/Executions.py
  agents-api/agents_api/queries/executions/get_execution.py
  agents-api/agents_api/queries/executions/get_paused_execution_token.py
  agents-api/agents_api/queries/executions/list_executions.py
  agents-api/tests/test_execution_queries.py
  integrations-service/integrations/autogen/Executions.py
  memory-store/migrations/000033_fix_latest_transitions.down.sql
  memory-store/migrations/000033_fix_latest_transitions.up.sql
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/executions/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1262 feat(agents-api): Add descriptive error messages
  agents-api/agents_api/web.py
  agents-api/tests/test_validation_errors.py
Labels: Review effort 3/5

#1247 feat(agents-api): Add ResponseItemList and other models to Responses' typespec
  agents-api/agents_api/autogen/Responses.py
  agents-api/agents_api/routers/responses/create_response.py
  agents-api/agents_api/routers/responses/get_response.py
  agents-api/agents_api/routers/utils/model_converters.py
  integrations-service/integrations/autogen/Responses.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/responses/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1261 fix: Miscellaneous fixes
  agents-api/agents_api/activities/execute_integration.py
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/common/interceptors.py
  agents-api/agents_api/common/protocol/models.py
  agents-api/agents_api/common/utils/__init__.py
  agents-api/agents_api/common/utils/db_exceptions.py
  agents-api/agents_api/common/utils/memory.py
  agents-api/agents_api/queries/docs/search_docs_by_text.py
  agents-api/agents_api/queries/docs/search_docs_hybrid.py
  agents-api/agents_api/queries/executions/create_execution_transition.py
  agents-api/agents_api/worker/codec.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/gunicorn_conf.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_activities_utils.py
  agents-api/tests/test_memory_utils.py
  agents-api/tests/test_pg_query_step.py
  agents-api/tests/test_tool_call_step.py
  agents-api/tests/test_workflow_helpers.py
  agents-api/tests/utils.py
  deploy/simple-docker-compose.yaml
  documentation/docs/concepts/docs.mdx
  documentation/docs/concepts/execution.mdx
  documentation/docs/concepts/sessions.mdx
  gateway/docker-compose.yml
  memory-store/docker-compose.yml
  monitoring/docker-compose.yml
Labels: Review effort 3/5

#1269 hotfix: Hotfix to fix port binding
  .cursorignore
  gateway/docker-compose.yml
  memory-store/README.md
  memory-store/docker-compose.yml
  monitoring/docker-compose.yml
Labels: Review effort 2/5

#1268 feat(agents-api): add web search tool call
  agents-api/agents_api/activities/tool_executor.py
  agents-api/agents_api/autogen/openapi_model.py
  agents-api/agents_api/env.py
  agents-api/agents_api/routers/responses/create_response.py
  agents-api/agents_api/routers/sessions/render.py
  agents-api/agents_api/routers/utils/model_converters.py
  agents-api/docker-compose.yml
Labels: Review effort 4/5

#1270 fix: Drop all the variants of searching functions before creating the…
  memory-store/migrations/000031_add_trigram_search.down.sql
  memory-store/migrations/000031_add_trigram_search.up.sql
  memory-store/migrations/000032_enhance_trigram_search.down.sql
  memory-store/migrations/000032_enhance_trigram_search.up.sql
Labels: Review effort 2/5

#1271 feat(memory-store): Switch cont agg/hypertables to hypercore
  agents-api/tests/utils.py
  memory-store/migrations/000034_switch_to_hypercore.down.sql
  memory-store/migrations/000034_switch_to_hypercore.up.sql
Labels: Review effort 2/5

#1277 chore(agents-api): Reasoning support & misc fixes in Responses
  agents-api/agents_api/autogen/Responses.py
  agents-api/agents_api/routers/responses/create_response.py
  agents-api/agents_api/routers/responses/get_response.py
  agents-api/agents_api/routers/utils/model_converters.py
  integrations-service/integrations/autogen/Responses.py
  typespec/responses/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1280 dev->main
  memory-store/migrations/000034_switch_to_hypercore.up.sql
Labels: Review effort 1/5

#1275 fix: Properly handle Jinja2 template errors
  agents-api/agents_api/common/utils/template.py
Labels: Review effort 2/5

#1282 Fix: Enable compression for transitions and entries tables
  memory-store/migrations/000034_switch_to_hypercore.down.sql
  memory-store/migrations/000034_switch_to_hypercore.up.sql
Labels: Review effort 2/5

#1281 fix(agents-api, deploy): minimize .env.example + misc fixes
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/env.py
  agents-api/docker-compose-api.yml
  deploy/.env.example
  deploy/litellm-config.yaml
  deploy/responses-build-docker-compose.yaml
  deploy/standalone-docker-compose.yaml
  memory-store/Dockerfile.migrations
Labels: Review effort 2/5

#1278 docs: initial docs added for response api
  agents-api/agents_api/routers/responses/get_response.py
  documentation/docs/integrations/search/algolia.mdx
  documentation/mint.json
  documentation/responses/concepts.mdx
  documentation/responses/quickstart.mdx
  documentation/responses/tutorials.mdx
Labels: Review effort 2/5

#1284 dev->main
  agents-api/agents_api/clients/pg.py
  agents-api/agents_api/common/utils/template.py
  agents-api/agents_api/queries/entries/get_history.py
  agents-api/agents_api/queries/entries/list_entries.py
  agents-api/agents_api/queries/executions/count_executions.py
  agents-api/agents_api/queries/executions/get_paused_execution_token.py
  agents-api/agents_api/queries/executions/list_execution_transitions.py
  agents-api/agents_api/queries/executions/list_executions.py
  agents-api/agents_api/queries/executions/prepare_execution_input.py
  agents-api/tests/test_execution_queries.py
  memory-store/migrations/000034_switch_to_hypercore.down.sql
  memory-store/migrations/000034_switch_to_hypercore.up.sql
Labels: Review effort 3/5

#1287 dev -> main
  agents-api/agents_api/queries/executions/create_execution_transition.py
  memory-store/migrations/000009_sessions.down.sql
  memory-store/migrations/000012_transitions.down.sql
  memory-store/migrations/000012_transitions.up.sql
  memory-store/migrations/000035_enhanced_indices.down.sql
  memory-store/migrations/000035_enhanced_indices.up.sql
Labels: Review effort 2/5

#1289 dev -> main (hotfix)
  agents-api/agents_api/queries/executions/get_execution.py
Labels: Review effort 1/5

#1239 feat(responses-api): Initialize Responses API
  .env.example
  README.md
  agents-api/agents_api/activities/tool_executor.py
  agents-api/agents_api/autogen/Chat.py
  agents-api/agents_api/autogen/Responses.py
  agents-api/agents_api/autogen/openapi_model.py
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/dependencies/developer_id.py
  agents-api/agents_api/env.py
  agents-api/agents_api/queries/entries/__init__.py
  agents-api/agents_api/routers/__init__.py
  agents-api/agents_api/routers/responses/__init__.py
  agents-api/agents_api/routers/responses/create_response.py
  agents-api/agents_api/routers/responses/get_response.py
  agents-api/agents_api/routers/responses/router.py
  agents-api/agents_api/routers/sessions/render.py
  agents-api/agents_api/routers/utils/model_converters.py
  agents-api/agents_api/web.py
  agents-api/docker-compose-api.yml
  agents-api/docker-compose.yml
  deploy/.env.example
  deploy/responses-build-docker-compose.yaml
  deploy/standalone-docker-compose.yaml
  documentation/docs/integrations/search/algolia.mdx
  documentation/docs/introduction/julep.mdx
  documentation/images/open-responses.jpg
  documentation/mint.json
  documentation/responses/cli.mdx
  documentation/responses/concepts.mdx
  documentation/responses/examples.mdx
  documentation/responses/quickstart.mdx
  documentation/responses/roadmap.mdx
  documentation/responses/tutorials.mdx
  integrations-service/docker-compose.yml
  integrations-service/integrations/autogen/Chat.py
  memory-store/Dockerfile.migrations
  typespec/chat/models.tsp
  typespec/main.tsp
  typespec/responses/endpoints.tsp
  typespec/responses/main.tsp
  typespec/responses/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5

#1292 fix(agents-api): add developer id to litellm requests
  agents-api/agents_api/activities/task_steps/prompt_step.py
  agents-api/agents_api/clients/litellm.py
  agents-api/agents_api/queries/chat/gather_messages.py
  agents-api/agents_api/routers/docs/embed.py
Labels: Review effort 2/5

#1263 feat(agents-api): Add static task validations to catch errors beforehand
  agents-api/agents_api/activities/execute_api_call.py
  agents-api/agents_api/activities/task_steps/base_evaluate.py
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/common/utils/task_validation.py
  agents-api/agents_api/env.py
  agents-api/agents_api/routers/tasks/create_or_update_task.py
  agents-api/agents_api/routers/tasks/create_task.py
  agents-api/tests/test_base_evaluate.py
  agents-api/tests/test_expression_validation.py
  agents-api/tests/test_task_validation.py
Labels: Review effort 4/5

#1298 hotfix(agents-api): Fix subquery cardinality issue
  agents-api/agents_api/queries/entries/get_history.py
  agents-api/agents_api/queries/entries/list_entries.py
  agents-api/agents_api/queries/executions/count_executions.py
  agents-api/agents_api/queries/executions/get_paused_execution_token.py
  agents-api/agents_api/queries/executions/list_execution_transitions.py
  agents-api/agents_api/queries/executions/prepare_execution_input.py
Labels: Review effort 2/5

#1299 chore(docker): update litellm-database image to version v1.65.0-stable
  llm-proxy/docker-compose.yml
Labels: Review effort 1/5
