Repository julep-ai/julep, pull requests merged in 2025-02, with the labels that each got.

#1122 feat(agents-api): enable label lookup + rename inputs/outputs
  agents-api/agents_api/autogen/Common.py
  agents-api/agents_api/autogen/Executions.py
  agents-api/agents_api/autogen/Tasks.py
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/queries/executions/create_execution_transition.py
  agents-api/agents_api/queries/executions/list_execution_transitions.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/tests/test_prepare_for_step.py
  agents-api/tests/test_task_execution_workflow.py
  integrations-service/integrations/autogen/Chat.py
  integrations-service/integrations/autogen/Common.py
  integrations-service/integrations/autogen/Executions.py
  integrations-service/integrations/autogen/Files.py
  integrations-service/integrations/autogen/Sessions.py
  integrations-service/integrations/autogen/Tasks.py
  integrations-service/integrations/autogen/Tools.py
  typespec/common/scalars.tsp
  typespec/executions/models.tsp
  typespec/tasks/steps.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 4

#1125 fix(cli): fixed lint error and added julep package in dependency
  cli/cli-reference.md
  cli/pyproject.toml
  cli/src/julep_cli/init.py
  cli/uv.lock
  documentation/docs/advanced/python-expression.mdx
Labels: Review effort [1-5]: 1

#1121 feat: Make csv stdlib module available in Python expressions
  agents-api/agents_api/activities/utils.py
  agents-api/tests/test_activities_utils.py
  documentation/docs/advanced/python-expression.mdx
Labels: Review effort [1-5]: 2

#1124 feat(cli): Add jsonschema for agent, task to use in yaml lsp for cli
  schemas/create_agent_request.json
  schemas/create_task_request.json
  schemas/walk.jq
  scripts/generate_openapi_code.sh
Labels: Review effort [1-5]: 2

#1123 feat: Make chat, agent and prompt step settings untyped
  agents-api/agents_api/activities/task_steps/prompt_step.py
  agents-api/agents_api/autogen/Agents.py
  agents-api/agents_api/autogen/Chat.py
  agents-api/agents_api/autogen/Tasks.py
  agents-api/agents_api/common/protocol/sessions.py
  agents-api/agents_api/queries/agents/create_agent.py
  agents-api/agents_api/queries/agents/create_or_update_agent.py
  agents-api/agents_api/queries/agents/patch_agent.py
  agents-api/agents_api/queries/agents/update_agent.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/poe_tasks.toml
  agents-api/tests/test_agent_queries.py
  integrations-service/integrations/autogen/Agents.py
  integrations-service/integrations/autogen/Chat.py
  integrations-service/integrations/autogen/Tasks.py
  typespec/agents/models.tsp
  typespec/chat/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort [1-5]: 3

#1127 fix(agents-api): fix ``Activity Task Failed`` and transitioning to error/cancelled
  agents-api/agents_api/activities/task_steps/base_evaluate.py
  agents-api/agents_api/common/exceptions/executions.py
  agents-api/agents_api/common/interceptors.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/tests/test_base_evaluate.py
Labels: Review effort [1-5]: 3

#1128 chore(cli): init + log improvements
  cli/pyproject.toml
  cli/src/julep_cli/executions.py
  cli/src/julep_cli/init.py
  cli/src/julep_cli/logs.py
  cli/src/julep_cli/utils.py
  cli/uv.lock
Labels: Review effort [1-5]: 2

#1129 feat(cli): Complete unimplemented sync options
  cli/src/julep_cli/executions.py
  cli/src/julep_cli/init.py
  cli/src/julep_cli/logs.py
  cli/src/julep_cli/ls.py
  cli/src/julep_cli/sync.py
  cli/src/julep_cli/tools.py
  cli/src/julep_cli/utils.py
  cli/uv.lock
Labels: Review effort [1-5]: 4

#1132 feat(cli): added watch mode to auto sync with file changes
  cli/pyproject.toml
  cli/src/julep_cli/chat.py
  cli/src/julep_cli/sync.py
  cli/uv.lock
Labels: Review effort [1-5]: 4

#1133 feat(cli): add agent flag to import and -h as an alias for help
  cli/src/julep_cli/__init__.py
  cli/src/julep_cli/app.py
  cli/src/julep_cli/importt.py
Labels: Review effort [1-5]: 2

#1134 feat(cli): More ls info & make run mirror executions create -> logs
  cli/src/julep_cli/executions.py
  cli/src/julep_cli/ls.py
  cli/src/julep_cli/run.py
Labels: Review effort [1-5]: 2

#1130 feat(cli): Make CLI interactive using questionary
  cli/pyproject.toml
  cli/src/julep_cli/__init__.py
  cli/src/julep_cli/__main__.py
  cli/src/julep_cli/agents.py
  cli/src/julep_cli/app.py
  cli/src/julep_cli/auth.py
  cli/src/julep_cli/chat.py
  cli/src/julep_cli/executions.py
  cli/src/julep_cli/importt.py
  cli/src/julep_cli/init.py
  cli/src/julep_cli/logs.py
  cli/src/julep_cli/ls.py
  cli/src/julep_cli/run.py
  cli/src/julep_cli/sync.py
  cli/src/julep_cli/tasks.py
  cli/src/julep_cli/tools.py
  cli/src/julep_cli/utils.py
  cli/src/julep_cli/wrapper.py
  cli/uv.lock
Labels: Review effort [1-5]: 4

#1136 fix(agents-api): fix subworkflows inputs
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/common/utils/workflows.py
Labels: Review effort [1-5]: 2

#1143 chore(cookbooks): updated cookbooks to point to prod
  cookbooks/00-Devfest-Email-Assistant.ipynb
  cookbooks/01-website-crawler.ipynb
  cookbooks/01-website-crawler.py
  cookbooks/02-sarcastic-news-headline-generator.ipynb
  cookbooks/02-sarcastic-news-headline-generator.py
  cookbooks/03-trip-planning-assistant.ipynb
  cookbooks/03-trip-planning-assistant.py
  cookbooks/04-hook-generator-trending-reels.ipynb
  cookbooks/04-hook-generator-trending-reels.py
  cookbooks/05-video-processing-with-natural-language.ipynb
  cookbooks/06-browser-use.ipynb
  cookbooks/07-personalized-research-assistant.ipynb
  cookbooks/08_customer_support_chatbot.ipynb
  cookbooks/09_companion_agent.ipynb
  cookbooks/10-crawling-and-rag.ipynb
Labels: Review effort [1-5]: 2

#1146 D/update cookbooks: Updated all cookbooks to new syntax and refactored docs
  cookbooks/00-Devfest-Email-Assistant.ipynb
  cookbooks/01-website-crawler.ipynb
  cookbooks/01-website-crawler.py
  cookbooks/02-sarcastic-news-headline-generator.ipynb
  cookbooks/02-sarcastic-news-headline-generator.py
  cookbooks/03-trip-planning-assistant.ipynb
  cookbooks/03-trip-planning-assistant.py
  cookbooks/04-hook-generator-trending-reels.ipynb
  cookbooks/04-hook-generator-trending-reels.py
  cookbooks/05-video-processing-with-natural-language.ipynb
  cookbooks/06-browser-use.ipynb
  cookbooks/07-personalized-research-assistant.ipynb
  cookbooks/08-rag-customer-support-chatbot.ipynb
  cookbooks/09-companion-agent.ipynb
  cookbooks/README.md
  documentation/docs/advanced/python-expression.mdx
  documentation/docs/advanced/types-of-task-steps.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/docs/tutorials/browser-use.mdx
  documentation/docs/tutorials/customer-support-rag.mdx
  documentation/docs/tutorials/trip-planning.mdx
  documentation/docs/tutorials/video-processing.mdx
Labels: Review effort [1-5]: 3

#1148 fix(agents-api): fix multiple transitions to error/cancelled
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
Labels: Review effort [1-5]: 2

#1151 feat(agents-api): enable backwards compatibility for old syntax
  agents-api/agents_api/activities/task_steps/base_evaluate.py
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/tests/test_base_evaluate.py
Labels: Review effort [1-5]: 3

#1154 fix(agents-api): Retry 524 http status code
  agents-api/agents_api/common/exceptions/tasks.py
Labels: Review effort [1-5]: 1

#1155 Misc improvements to docs
  documentation/docs/advanced/lifecycle.mdx
  documentation/docs/concepts/docs.mdx
  documentation/docs/concepts/sessions.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/docs/julepcli/commands.mdx
  documentation/docs/julepcli/introduction.mdx
  documentation/docs/tutorials/browser-use.mdx
  documentation/guides/getting-started/basic-agent-creation.mdx
  documentation/guides/getting-started/chat-with-an-agent.mdx
  documentation/guides/getting-started/create-and-execute-julep-task.mdx
  documentation/guides/getting-started/task-workflow-basics.mdx
  documentation/mint.json
Labels: Review effort 4/5

#1156 chore: updated cookbooks + tutorials sec
  cookbooks/00-Devfest-Email-Assistant.ipynb
  cookbooks/01-website-crawler.ipynb
  cookbooks/02-sarcastic-news-headline-generator.ipynb
  cookbooks/03-trip-planning-assistant.ipynb
  cookbooks/04-hook-generator-trending-reels.ipynb
  cookbooks/05-video-processing-with-natural-language.ipynb
  cookbooks/06-browser-use.ipynb
  cookbooks/07-personalized-research-assistant.ipynb
  cookbooks/08-rag-customer-support-chatbot.ipynb
  cookbooks/09-companion-agent.ipynb
  cookbooks/README.md
  documentation/docs/tutorials/customer-support-rag.mdx
  documentation/docs/tutorials/rag-chatbot.mdx
  documentation/mint.json
Labels: Review effort 2/5

#1153 Prometheus metrics
  agents-api/agents_api/app.py
  agents-api/agents_api/metrics/counters.py
  agents-api/agents_api/queries/agents/create_agent.py
  agents-api/agents_api/queries/agents/create_or_update_agent.py
  agents-api/agents_api/queries/agents/patch_agent.py
  agents-api/agents_api/queries/agents/update_agent.py
  agents-api/agents_api/queries/docs/create_doc.py
  agents-api/agents_api/queries/entries/create_entries.py
  agents-api/agents_api/queries/entries/delete_entries.py
  agents-api/agents_api/queries/entries/list_entries.py
  agents-api/agents_api/queries/executions/create_execution.py
  agents-api/agents_api/queries/executions/create_execution_transition.py
  agents-api/agents_api/queries/executions/create_temporal_lookup.py
  agents-api/agents_api/queries/files/create_file.py
  agents-api/agents_api/queries/files/delete_file.py
  agents-api/agents_api/queries/sessions/count_sessions.py
  agents-api/agents_api/queries/sessions/create_or_update_session.py
  agents-api/agents_api/queries/sessions/create_session.py
  agents-api/agents_api/queries/sessions/delete_session.py
  agents-api/agents_api/queries/sessions/get_session.py
  agents-api/agents_api/queries/sessions/list_sessions.py
  agents-api/agents_api/queries/sessions/patch_session.py
  agents-api/agents_api/queries/sessions/update_session.py
  agents-api/agents_api/queries/tasks/create_or_update_task.py
  agents-api/agents_api/queries/tasks/create_task.py
  agents-api/agents_api/queries/tasks/patch_task.py
  agents-api/agents_api/queries/tasks/update_task.py
  agents-api/agents_api/queries/tools/create_tools.py
  agents-api/agents_api/queries/tools/patch_tool.py
  agents-api/agents_api/queries/tools/update_tool.py
  agents-api/agents_api/queries/users/create_or_update_user.py
  agents-api/agents_api/queries/users/create_user.py
  agents-api/agents_api/queries/users/patch_user.py
  agents-api/agents_api/queries/users/update_user.py
  monitoring/grafana/provisioning/dashboards/queries-metrics.json
  monitoring/grafana/provisioning/dashboards/requests-metrics.json
  monitoring/prometheus/config/prometheus.yml
Labels: Review effort [1-5]: 3

#1158 feat(agents-api): make ``parallelism = task_max_parallelism`` the default for MapReduce
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/tests/test_workflow_helpers.py
Labels: Review effort 2/5

#1160 chore: updated changelog to new syntax
  CHANGELOG.md
  scripts/generate_changelog.py
  scripts/templates/changelog.yaml
Labels: Review effort 2/5

#1165 feat(agents-api): Allow execution_id filtering for child workflows
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
Labels: Review effort 2/5

#1164 chore(docs): updated type of task steps page
  CHANGELOG.md
  cookbooks/IDEAS.md
  cookbooks/README.md
  documentation/docs/advanced/new-syntax.mdx
  documentation/docs/advanced/types-of-task-steps.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/mint.json
  scripts/templates/header.html
Labels: Review effort 1/5

#1168 docs(CONTRIBUTING | integrations): Add guidelines for adding new integrations
  CONTRIBUTING.md
  documentation/docs/integrations/contributing-integrations.mdx
  documentation/docs/introduction/install.mdx
  documentation/mint.json
Labels: Review effort 1/5

#1167 fix(integrations): updated ffmpeg file input to support list of strings
  agents-api/agents_api/autogen/Tools.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  documentation/docs/integrations/media_file_processing/cloudinary.mdx
  documentation/docs/integrations/media_file_processing/ffmpeg.mdx
  integrations-service/integrations/autogen/Tools.py
  integrations-service/integrations/utils/integrations/ffmpeg.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  scripts/generate_changelog.py
  typespec/tools/ffmpeg.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1169 feat(agents-api): add ``default_system_template`` to agents
  agents-api/agents_api/autogen/Agents.py
  agents-api/agents_api/autogen/Sessions.py
  agents-api/agents_api/common/protocol/sessions.py
  agents-api/agents_api/queries/agents/create_agent.py
  agents-api/agents_api/queries/agents/create_or_update_agent.py
  agents-api/agents_api/queries/agents/get_agent.py
  agents-api/agents_api/queries/agents/list_agents.py
  agents-api/agents_api/queries/agents/patch_agent.py
  agents-api/agents_api/queries/agents/update_agent.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  integrations-service/integrations/autogen/Agents.py
  integrations-service/integrations/autogen/Sessions.py
  memory-store/migrations/000025_default_system_template.down.sql
  memory-store/migrations/000025_default_system_template.up.sql
  typespec/agents/models.tsp
  typespec/sessions/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 3/5

#1171 feat(agents-api): treat leaf nodes as fstrings
  agents-api/agents_api/activities/task_steps/base_evaluate.py
  agents-api/tests/test_base_evaluate.py
Labels: Review effort 2/5

#1176 chore: Bump up litellm version to latest stable release
  llm-proxy/docker-compose.yml
Labels: Review effort 1/5

#1175 fix(agents-api): resolve continue as new issue and add a start_workflow interceptor
  agents-api/agents_api/clients/temporal.py
  agents-api/agents_api/common/interceptors.py
Labels: Review effort 2/5

#1181 feat(litellm): added support for cerebras models + docs update
  .env.example
  deploy/simple-docker-compose.yaml
  documentation/docs/advanced/chat.mdx
  documentation/docs/concepts/agents.mdx
  documentation/docs/concepts/docs.mdx
  documentation/docs/concepts/sessions.mdx
  documentation/docs/integrations/supported-models.mdx
  documentation/mint.json
  llm-proxy/docker-compose.yml
  llm-proxy/litellm-config.yaml
Labels: Review effort 2/5

#1178 feat(agents-api, memory-store): resolve subworkflow and subworkflow in parallel steps inputs
  agents-api/agents_api/autogen/Executions.py
  agents-api/agents_api/clients/temporal.py
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/queries/executions/create_execution_transition.py
  agents-api/agents_api/queries/executions/get_execution_transition.py
  agents-api/agents_api/queries/executions/list_execution_transitions.py
  agents-api/agents_api/routers/tasks/list_execution_transitions.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/agents_api/workflows/task_execution/transition.py
  agents-api/tests/fixtures.py
  agents-api/tests/test_base_evaluate.py
  agents-api/tests/test_execution_queries.py
  agents-api/tests/test_prepare_for_step.py
  agents-api/tests/test_task_execution_workflow.py
  agents-api/tests/test_task_routes.py
  agents-api/tests/test_workflow_helpers.py
  agents-api/tests/utils.py
  integrations-service/integrations/autogen/Executions.py
  memory-store/migrations/000026_transition_cursor.down.sql
  memory-store/migrations/000026_transition_cursor.up.sql
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/executions/models.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5

#1184 fix(memory-store): add a call to decompress transitions chunks
  memory-store/migrations/000026_transition_cursor.up.sql
Labels: Review effort 1/5

#1185 feat(agents-api): enable self recursion
  agents-api/agents_api/queries/executions/create_execution_transition.py
  agents-api/tests/test_execution_queries.py
Labels: Review effort 2/5

#1182 feat(agents-api): Make execution id temporal search attribute configurable
  .env.example
  agents-api/agents_api/clients/temporal.py
  agents-api/agents_api/env.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/docker-compose.yml
Labels: Review effort 2/5

#1170 feat: Add postgraphile service
  docker-compose.yml
  graphql/docker-compose.yml
  memory-store/migrations/000027_add_postgraphile.down.sql
  memory-store/migrations/000027_add_postgraphile.up.sql
Labels: Review effort 4/5

#1189 fix(agents-api): hotfix for get/list executions
  agents-api/agents_api/queries/executions/get_execution.py
  agents-api/agents_api/queries/executions/list_executions.py
Labels: Review effort 3/5

#1186 fix(agents-api): properly exit a subworkflow with return step
  agents-api/agents_api/common/protocol/tasks.py
  agents-api/agents_api/routers/tasks/create_task_execution.py
  agents-api/agents_api/workflows/task_execution/__init__.py
  agents-api/agents_api/workflows/task_execution/helpers.py
  agents-api/tests/test_task_execution_workflow.py
  agents-api/tests/test_workflow_helpers.py
Labels: Review effort 4/5

#1187 feat(agents-api): Add humanize_text function to supported PyExp functions
  .env.example
  agents-api/agents_api/activities/humanization_utils.py
  agents-api/agents_api/activities/utils.py
  agents-api/agents_api/env.py
  agents-api/docker-compose.yml
  agents-api/pyproject.toml
  agents-api/tests/test_activities_utils.py
  agents-api/uv.lock
  documentation/docs/advanced/python-expression.mdx
Labels: Review effort 4/5

#1191 fix(agents-api): resolve ``dummy_tool`` issue
  agents-api/agents_api/clients/litellm.py
  agents-api/tests/test_litellm_utils.py
Labels: Review effort 2/5

#1196 fix(agents-api): allow nested steps in IfElse step
  .github/workflows/generate-openapi-code-from-typespec.yml
  agents-api/agents_api/autogen/Tasks.py
  integrations-service/integrations/autogen/Tasks.py
  typespec/tasks/steps.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5

#1183 F/rag-improv: Misc RAG Improvements
  .github/workflows/generate-openapi-code-from-typespec.yml
  agents-api/agents_api/autogen/Docs.py
  agents-api/agents_api/autogen/Sessions.py
  agents-api/agents_api/autogen/Tasks.py
  agents-api/agents_api/common/utils/get_doc_search.py
  agents-api/agents_api/queries/chat/gather_messages.py
  agents-api/agents_api/routers/docs/search_docs.py
  agents-api/agents_api/routers/sessions/chat.py
  agents-api/tests/test_get_doc_search.py
  documentation/docs/advanced/chat.mdx
  documentation/docs/advanced/types-of-task-steps.mdx
  documentation/docs/concepts/agents.mdx
  documentation/docs/concepts/docs.mdx
  documentation/docs/concepts/execution.mdx
  documentation/docs/concepts/sessions.mdx
  documentation/docs/concepts/tasks.mdx
  documentation/docs/concepts/users.mdx
  integrations-service/integrations/autogen/Docs.py
  integrations-service/integrations/autogen/Sessions.py
  integrations-service/integrations/autogen/Tasks.py
  schemas/create_agent_request.json
  schemas/create_task_request.json
  typespec/docs/models.tsp
  typespec/sessions/models.tsp
  typespec/tasks/steps.tsp
  typespec/tsp-output/@typespec/openapi3/openapi-1.0.0.yaml
Labels: Review effort 4/5

#1199 feat(agents-api,memory-store): Disallow creating docs with duplicate content
  agents-api/agents_api/common/utils/db_exceptions.py
  agents-api/pyproject.toml
  agents-api/tests/test_docs_routes.py
  agents-api/uv.lock
  memory-store/migrations/000029_duplicate_doc_prevention.down.sql
  memory-store/migrations/000029_duplicate_doc_prevention.up.sql
Labels: Review effort 4/5

#1197 fix: Add new hybrid search implementation
  memory-store/migrations/000028_new_hybrid_search_implementation.down.sql
  memory-store/migrations/000028_new_hybrid_search_implementation.up.sql
Labels: Review effort 4/5
